//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moryx.Products.UI.Interaction.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moryx.Products.UI.Interaction.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AddRecipeDialogView_Cancel {
            get {
                return ResourceManager.GetString("AddRecipeDialogView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string AddRecipeDialogView_Create {
            get {
                return ResourceManager.GetString("AddRecipeDialogView_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AddRecipeDialogView_RecipeName {
            get {
                return ResourceManager.GetString("AddRecipeDialogView_RecipeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string AddRecipeDialogView_Type {
            get {
                return ResourceManager.GetString("AddRecipeDialogView_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workplan.
        /// </summary>
        public static string AddRecipeDialogView_Workplan {
            get {
                return ResourceManager.GetString("AddRecipeDialogView_Workplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new recipe.
        /// </summary>
        public static string AddRecipeDialogViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AddRecipeDialogViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string CollectionPartConnectorView_Add {
            get {
                return ResourceManager.GetString("CollectionPartConnectorView_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string CollectionPartConnectorView_Remove {
            get {
                return ResourceManager.GetString("CollectionPartConnectorView_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CreateRevisionView_Cancel {
            get {
                return ResourceManager.GetString("CreateRevisionView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateRevisionView_Create {
            get {
                return ResourceManager.GetString("CreateRevisionView_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product:.
        /// </summary>
        public static string CreateRevisionView_Product {
            get {
                return ResourceManager.GetString("CreateRevisionView_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision:.
        /// </summary>
        public static string CreateRevisionView_Revision {
            get {
                return ResourceManager.GetString("CreateRevisionView_Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given identity and revision is conflicted with an existing..
        /// </summary>
        public static string CreateRevisionViewModel_ConflictedIdentity {
            get {
                return ResourceManager.GetString("CreateRevisionViewModel_ConflictedIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Revision.
        /// </summary>
        public static string CreateRevisionViewModel_DisplayName {
            get {
                return ResourceManager.GetString("CreateRevisionViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision not available.
        /// </summary>
        public static string CreateRevisionViewModel_RevisionNotAvailable {
            get {
                return ResourceManager.GetString("CreateRevisionViewModel_RevisionNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification.
        /// </summary>
        public static string DefaultRecipeDetailsView_General_Classification {
            get {
                return ResourceManager.GetString("DefaultRecipeDetailsView_General_Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DefaultRecipeDetailsView_General_Name {
            get {
                return ResourceManager.GetString("DefaultRecipeDetailsView_General_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string DefaultRecipeDetailsView_General_Title {
            get {
                return ResourceManager.GetString("DefaultRecipeDetailsView_General_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workplan.
        /// </summary>
        public static string DefaultRecipeDetailsView_General_Workplan {
            get {
                return ResourceManager.GetString("DefaultRecipeDetailsView_General_Workplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recipe does not have any configurable properties..
        /// </summary>
        public static string DefaultRecipeDetailsView_NoProperties {
            get {
                return ResourceManager.GetString("DefaultRecipeDetailsView_NoProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string DefaultRecipeDetailsView_Properties {
            get {
                return ResourceManager.GetString("DefaultRecipeDetailsView_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DuplicateProductDialogView_Cancel {
            get {
                return ResourceManager.GetString("DuplicateProductDialogView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        public static string DuplicateProductDialogView_Clone {
            get {
                return ResourceManager.GetString("DuplicateProductDialogView_Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string DuplicateProductDialogView_Identifier {
            get {
                return ResourceManager.GetString("DuplicateProductDialogView_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision.
        /// </summary>
        public static string DuplicateProductDialogView_Revision {
            get {
                return ResourceManager.GetString("DuplicateProductDialogView_Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given identity and revision is conflicted with an existing..
        /// </summary>
        public static string DuplicateProductDialogViewModel_ConflictedIdentity {
            get {
                return ResourceManager.GetString("DuplicateProductDialogViewModel_ConflictedIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate product &apos;{0}&apos;.
        /// </summary>
        public static string DuplicateProductDialogViewModel_DisplayName {
            get {
                return ResourceManager.GetString("DuplicateProductDialogViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ImportView_Cancel {
            get {
                return ResourceManager.GetString("ImportView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import product using importers..
        /// </summary>
        public static string ImportView_Description {
            get {
                return ResourceManager.GetString("ImportView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string ImportView_ImportProduct {
            get {
                return ResourceManager.GetString("ImportView_ImportProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Importer.
        /// </summary>
        public static string ImportViewModel_DisplayName {
            get {
                return ResourceManager.GetString("ImportViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all required fields!.
        /// </summary>
        public static string ImportViewModel_Fill_required_fields {
            get {
                return ResourceManager.GetString("ImportViewModel_Fill_required_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while creating the product..
        /// </summary>
        public static string ImportViewModel_Import_error {
            get {
                return ResourceManager.GetString("ImportViewModel_Import_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the current input..
        /// </summary>
        public static string ImportViewModel_Import_error_info {
            get {
                return ResourceManager.GetString("ImportViewModel_Import_error_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string ModuleController_DisplayName {
            get {
                return ResourceManager.GetString("ModuleController_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a part from the list.
        /// </summary>
        public static string PartsAspectView_SelectPart {
            get {
                return ResourceManager.GetString("PartsAspectView_SelectPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts.
        /// </summary>
        public static string PartsAspectViewModel_DisplayName {
            get {
                return ResourceManager.GetString("PartsAspectViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no relevant aspects for the selected product..
        /// </summary>
        public static string ProductDetailsViewModelBase_No_relevant_aspects {
            get {
                return ResourceManager.GetString("ProductDetailsViewModelBase_No_relevant_aspects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ProductsWorkspaceView_Cancel {
            get {
                return ResourceManager.GetString("ProductsWorkspaceView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string ProductsWorkspaceView_Duplicate {
            get {
                return ResourceManager.GetString("ProductsWorkspaceView_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ProductsWorkspaceView_Edit {
            get {
                return ResourceManager.GetString("ProductsWorkspaceView_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string ProductsWorkspaceView_Filter {
            get {
                return ResourceManager.GetString("ProductsWorkspaceView_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string ProductsWorkspaceView_Filter_Identifier {
            get {
                return ResourceManager.GetString("ProductsWorkspaceView_Filter_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ProductsWorkspaceView_Filter_Name {
            get {
                return ResourceManager.GetString("ProductsWorkspaceView_Filter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ProductsWorkspaceView_Filter_Reset {
            get {
                return ResourceManager.GetString("ProductsWorkspaceView_Filter_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisions.
        /// </summary>
        public static string ProductsWorkspaceView_Filter_Revisions {
            get {
                return ResourceManager.GetString("ProductsWorkspaceView_Filter_Revisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector.
        /// </summary>
        public static string ProductsWorkspaceView_Filter_Selector {
            get {
                return ResourceManager.GetString("ProductsWorkspaceView_Filter_Selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier:.
        /// </summary>
        public static string ProductsWorkspaceView_General_Identifier {
            get {
                return ResourceManager.GetString("ProductsWorkspaceView_General_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string ProductsWorkspaceView_General_Name {
            get {
                return ResourceManager.GetString("ProductsWorkspaceView_General_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string ProductsWorkspaceView_General_Title {
            get {
                return ResourceManager.GetString("ProductsWorkspaceView_General_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string ProductsWorkspaceView_Import {
            get {
                return ResourceManager.GetString("ProductsWorkspaceView_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string ProductsWorkspaceView_Remove {
            get {
                return ResourceManager.GetString("ProductsWorkspaceView_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisions.
        /// </summary>
        public static string ProductsWorkspaceView_Revisions {
            get {
                return ResourceManager.GetString("ProductsWorkspaceView_Revisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ProductsWorkspaceView_Save {
            get {
                return ResourceManager.GetString("ProductsWorkspaceView_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string ProductsWorkspaceView_Title {
            get {
                return ResourceManager.GetString("ProductsWorkspaceView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving takes longer than expected. Refresh again later..
        /// </summary>
        public static string ProductsWorkspaceViewModel_SaveTimeOut_Message {
            get {
                return ResourceManager.GetString("ProductsWorkspaceViewModel_SaveTimeOut_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Timeout.
        /// </summary>
        public static string ProductsWorkspaceViewModel_SaveTimeOut_Title {
            get {
                return ResourceManager.GetString("ProductsWorkspaceViewModel_SaveTimeOut_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a product from the tree on the left side..
        /// </summary>
        public static string ProductsWorkspaceViewModel_SelectProduct {
            get {
                return ResourceManager.GetString("ProductsWorkspaceViewModel_SelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string PropertiesAspectViewModel_DisplayName {
            get {
                return ResourceManager.GetString("PropertiesAspectViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a recipe from the list.
        /// </summary>
        public static string RecipeAspectView_NonRecipeSelected {
            get {
                return ResourceManager.GetString("RecipeAspectView_NonRecipeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save recipe:.
        /// </summary>
        public static string RecipeDetailsViewModelBase_ErrorSavingRecipe_Message {
            get {
                return ResourceManager.GetString("RecipeDetailsViewModelBase_ErrorSavingRecipe_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string RecipeDetailsViewModelBase_ErrorSavingRecipe_Title {
            get {
                return ResourceManager.GetString("RecipeDetailsViewModelBase_ErrorSavingRecipe_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string RecipesAspectView_AddRecipe {
            get {
                return ResourceManager.GetString("RecipesAspectView_AddRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RecipesAspectView_RemoveRecipe {
            get {
                return ResourceManager.GetString("RecipesAspectView_RemoveRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes.
        /// </summary>
        public static string RecipesAspectViewModel_DisplayName {
            get {
                return ResourceManager.GetString("RecipesAspectViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string RecipeWorkspaceView_Cancel {
            get {
                return ResourceManager.GetString("RecipeWorkspaceView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string RecipeWorkspaceView_Edit {
            get {
                return ResourceManager.GetString("RecipeWorkspaceView_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes:.
        /// </summary>
        public static string RecipeWorkspaceView_Recipes {
            get {
                return ResourceManager.GetString("RecipeWorkspaceView_Recipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string RecipeWorkspaceView_Save {
            get {
                return ResourceManager.GetString("RecipeWorkspaceView_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workplan:.
        /// </summary>
        public static string RecipeWorkspaceView_Workplan {
            get {
                return ResourceManager.GetString("RecipeWorkspaceView_Workplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while receiving recipes..
        /// </summary>
        public static string RecipeWorkspaceViewModel_ErrorLoadingRecipes_Message {
            get {
                return ResourceManager.GetString("RecipeWorkspaceViewModel_ErrorLoadingRecipes_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string RecipeWorkspaceViewModel_ErrorLoadingRecipes_Title {
            get {
                return ResourceManager.GetString("RecipeWorkspaceViewModel_ErrorLoadingRecipes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while receiving workplans..
        /// </summary>
        public static string RecipeWorkspaceViewModel_ErrorLoadingWorkplans {
            get {
                return ResourceManager.GetString("RecipeWorkspaceViewModel_ErrorLoadingWorkplans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a recipe from the list.
        /// </summary>
        public static string RecipeWorkspaceViewModel_SelectRecipe {
            get {
                return ResourceManager.GetString("RecipeWorkspaceViewModel_SelectRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This product is used in the following products:.
        /// </summary>
        public static string RelationsAspectView_Description {
            get {
                return ResourceManager.GetString("RelationsAspectView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relations:.
        /// </summary>
        public static string RelationsAspectView_ListTitle {
            get {
                return ResourceManager.GetString("RelationsAspectView_ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string RelationsAspectView_ListView_Identifier {
            get {
                return ResourceManager.GetString("RelationsAspectView_ListView_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string RelationsAspectView_ListView_Name {
            get {
                return ResourceManager.GetString("RelationsAspectView_ListView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision.
        /// </summary>
        public static string RelationsAspectView_ListView_Revision {
            get {
                return ResourceManager.GetString("RelationsAspectView_ListView_Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relations.
        /// </summary>
        public static string RelationsAspectViewModel_DisplayName {
            get {
                return ResourceManager.GetString("RelationsAspectViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string RemoveProductView_Cancel {
            get {
                return ResourceManager.GetString("RemoveProductView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following product will be irreversible removed:.
        /// </summary>
        public static string RemoveProductView_Description {
            get {
                return ResourceManager.GetString("RemoveProductView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In use by:.
        /// </summary>
        public static string RemoveProductView_InUseBy {
            get {
                return ResourceManager.GetString("RemoveProductView_InUseBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveProductView_RemoveProduct {
            get {
                return ResourceManager.GetString("RemoveProductView_RemoveProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Product.
        /// </summary>
        public static string RemoveProductViewModel_DisplayName {
            get {
                return ResourceManager.GetString("RemoveProductViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product was not removed!.
        /// </summary>
        public static string RemoveProductViewModel_ErrorWhileRemove {
            get {
                return ResourceManager.GetString("RemoveProductViewModel_ErrorWhileRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product cannot be removed because it is still used in other products.
        /// </summary>
        public static string RemoveProductViewModel_NonDeletableHint {
            get {
                return ResourceManager.GetString("RemoveProductViewModel_NonDeletableHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string RevisionsView_Close {
            get {
                return ResourceManager.GetString("RevisionsView_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string RevisionsView_Create {
            get {
                return ResourceManager.GetString("RevisionsView_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string RevisionsView_Open {
            get {
                return ResourceManager.GetString("RevisionsView_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisions.
        /// </summary>
        public static string RevisionsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("RevisionsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string SelectPartLinkDialogView_Apply {
            get {
                return ResourceManager.GetString("SelectPartLinkDialogView_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SelectPartLinkDialogView_Cancel {
            get {
                return ResourceManager.GetString("SelectPartLinkDialogView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SelectPartLinkDialogView_Search {
            get {
                return ResourceManager.GetString("SelectPartLinkDialogView_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a product from the list.
        /// </summary>
        public static string SelectPartLinkDialogView_SelectProduct {
            get {
                return ResourceManager.GetString("SelectPartLinkDialogView_SelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Part.
        /// </summary>
        public static string SelectPartLinkDialogViewModel_DisplayName {
            get {
                return ResourceManager.GetString("SelectPartLinkDialogViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string SinglePartConnectorPartView_Change {
            get {
                return ResourceManager.GetString("SinglePartConnectorPartView_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string SinglePartConnectorPartView_Clear {
            get {
                return ResourceManager.GetString("SinglePartConnectorPartView_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string SinglePartConnectorPartView_DefaultPartConnectorName {
            get {
                return ResourceManager.GetString("SinglePartConnectorPartView_DefaultPartConnectorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following configuration edits the properties of the link to the product..
        /// </summary>
        public static string SinglePartConnectorPartView_Description {
            get {
                return ResourceManager.GetString("SinglePartConnectorPartView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link does not provide any configuration..
        /// </summary>
        public static string SinglePartConnectorPartView_EmptyProperties {
            get {
                return ResourceManager.GetString("SinglePartConnectorPartView_EmptyProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no product selected for this link..
        /// </summary>
        public static string SinglePartConnectorPartView_NullLink {
            get {
                return ResourceManager.GetString("SinglePartConnectorPartView_NullLink", resourceCulture);
            }
        }
    }
}
