//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marvin.Products.UI.ProductService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductCustomization", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Products.Management.Modification")]
    [System.SerializableAttribute()]
    public partial class ProductCustomization : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasRecipesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.ProductImporter[] ImportersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ProductTypesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] RecipeTypesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ReleasedProductsEditableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.StorageValue[] StorageValuesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasRecipes {
            get {
                return this.HasRecipesField;
            }
            set {
                if ((this.HasRecipesField.Equals(value) != true)) {
                    this.HasRecipesField = value;
                    this.RaisePropertyChanged("HasRecipes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.ProductImporter[] Importers {
            get {
                return this.ImportersField;
            }
            set {
                if ((object.ReferenceEquals(this.ImportersField, value) != true)) {
                    this.ImportersField = value;
                    this.RaisePropertyChanged("Importers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ProductTypes {
            get {
                return this.ProductTypesField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductTypesField, value) != true)) {
                    this.ProductTypesField = value;
                    this.RaisePropertyChanged("ProductTypes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] RecipeTypes {
            get {
                return this.RecipeTypesField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipeTypesField, value) != true)) {
                    this.RecipeTypesField = value;
                    this.RaisePropertyChanged("RecipeTypes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReleasedProductsEditable {
            get {
                return this.ReleasedProductsEditableField;
            }
            set {
                if ((this.ReleasedProductsEditableField.Equals(value) != true)) {
                    this.ReleasedProductsEditableField = value;
                    this.RaisePropertyChanged("ReleasedProductsEditable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.StorageValue[] StorageValues {
            get {
                return this.StorageValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.StorageValuesField, value) != true)) {
                    this.StorageValuesField = value;
                    this.RaisePropertyChanged("StorageValues");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductImporter", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Products.Management.Modification")]
    [System.SerializableAttribute()]
    public partial class ProductImporter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Serialization.Entry ParametersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Serialization.Entry Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StorageValue", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Products.Management.Modification")]
    [System.SerializableAttribute()]
    public partial class StorageValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ValuesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Values {
            get {
                return this.ValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.ValuesField, value) != true)) {
                    this.ValuesField = value;
                    this.RaisePropertyChanged("Values");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductStructureEntry", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Products.Management", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ProductStructureEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.BranchType BranchTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.ProductStructureEntry[] BranchesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaterialNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short RevisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.ProductState StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.BranchType BranchType {
            get {
                return this.BranchTypeField;
            }
            set {
                if ((this.BranchTypeField.Equals(value) != true)) {
                    this.BranchTypeField = value;
                    this.RaisePropertyChanged("BranchType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.ProductStructureEntry[] Branches {
            get {
                return this.BranchesField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchesField, value) != true)) {
                    this.BranchesField = value;
                    this.RaisePropertyChanged("Branches");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaterialNumber {
            get {
                return this.MaterialNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MaterialNumberField, value) != true)) {
                    this.MaterialNumberField = value;
                    this.RaisePropertyChanged("MaterialNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Revision {
            get {
                return this.RevisionField;
            }
            set {
                if ((this.RevisionField.Equals(value) != true)) {
                    this.RevisionField = value;
                    this.RaisePropertyChanged("Revision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.ProductState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BranchType", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Products.Management")]
    public enum BranchType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Group = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Product = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartCollector = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductState", Namespace="http://schemas.datacontract.org/2004/07/Marvin.AbstractionLayer")]
    public enum ProductState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Created = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Released = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductModel", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Products.Management.Modification", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ProductModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.ProductFile[] FilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.PartConnector[] PartsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Serialization.Entry PropertiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.RecipeModel[] RecipesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short RevisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.ProductState StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.ProductFile[] Files {
            get {
                return this.FilesField;
            }
            set {
                if ((object.ReferenceEquals(this.FilesField, value) != true)) {
                    this.FilesField = value;
                    this.RaisePropertyChanged("Files");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identifier {
            get {
                return this.IdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentifierField, value) != true)) {
                    this.IdentifierField = value;
                    this.RaisePropertyChanged("Identifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.PartConnector[] Parts {
            get {
                return this.PartsField;
            }
            set {
                if ((object.ReferenceEquals(this.PartsField, value) != true)) {
                    this.PartsField = value;
                    this.RaisePropertyChanged("Parts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Serialization.Entry Properties {
            get {
                return this.PropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertiesField, value) != true)) {
                    this.PropertiesField = value;
                    this.RaisePropertyChanged("Properties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.RecipeModel[] Recipes {
            get {
                return this.RecipesField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipesField, value) != true)) {
                    this.RecipesField = value;
                    this.RaisePropertyChanged("Recipes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Revision {
            get {
                return this.RevisionField;
            }
            set {
                if ((this.RevisionField.Equals(value) != true)) {
                    this.RevisionField = value;
                    this.RaisePropertyChanged("Revision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.ProductState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductFile", Namespace="http://schemas.datacontract.org/2004/07/Marvin.AbstractionLayer")]
    [System.SerializableAttribute()]
    public partial class ProductFile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.FileType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] File {
            get {
                return this.FileField;
            }
            set {
                if ((object.ReferenceEquals(this.FileField, value) != true)) {
                    this.FileField = value;
                    this.RaisePropertyChanged("File");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.FileType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartConnector", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Products.Management.Modification", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class PartConnector : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCollectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.PartModel[] PartsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Serialization.Entry PropertyTemplatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCollection {
            get {
                return this.IsCollectionField;
            }
            set {
                if ((this.IsCollectionField.Equals(value) != true)) {
                    this.IsCollectionField = value;
                    this.RaisePropertyChanged("IsCollection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.PartModel[] Parts {
            get {
                return this.PartsField;
            }
            set {
                if ((object.ReferenceEquals(this.PartsField, value) != true)) {
                    this.PartsField = value;
                    this.RaisePropertyChanged("Parts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Serialization.Entry PropertyTemplates {
            get {
                return this.PropertyTemplatesField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyTemplatesField, value) != true)) {
                    this.PropertyTemplatesField = value;
                    this.RaisePropertyChanged("PropertyTemplates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecipeModel", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Products.Management.Modification", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class RecipeModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.RecipeClassificationModel ClassificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Serialization.Entry IngredientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RevisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.RecipeState StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long WorkplanIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.RecipeClassificationModel Classification {
            get {
                return this.ClassificationField;
            }
            set {
                if ((this.ClassificationField.Equals(value) != true)) {
                    this.ClassificationField = value;
                    this.RaisePropertyChanged("Classification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Serialization.Entry Ingredients {
            get {
                return this.IngredientsField;
            }
            set {
                if ((object.ReferenceEquals(this.IngredientsField, value) != true)) {
                    this.IngredientsField = value;
                    this.RaisePropertyChanged("Ingredients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Revision {
            get {
                return this.RevisionField;
            }
            set {
                if ((this.RevisionField.Equals(value) != true)) {
                    this.RevisionField = value;
                    this.RaisePropertyChanged("Revision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.RecipeState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long WorkplanId {
            get {
                return this.WorkplanIdField;
            }
            set {
                if ((this.WorkplanIdField.Equals(value) != true)) {
                    this.WorkplanIdField = value;
                    this.RaisePropertyChanged("WorkplanId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileType", Namespace="http://schemas.datacontract.org/2004/07/Marvin.AbstractionLayer")]
    public enum FileType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Image = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Text = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Binary = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartModel", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Products.Management.Modification", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class PartModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.ProductModel ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Serialization.Entry PropertiesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.ProductModel Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Serialization.Entry Properties {
            get {
                return this.PropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertiesField, value) != true)) {
                    this.PropertiesField = value;
                    this.RaisePropertyChanged("Properties");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecipeClassificationModel", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Products.Management.Modification")]
    public enum RecipeClassificationModel : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unset = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Default = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Alternative = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Intermediate = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Part = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecipeState", Namespace="http://schemas.datacontract.org/2004/07/Marvin.AbstractionLayer")]
    public enum RecipeState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        New = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Released = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Revoked = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductRevisionEntry", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Products.Management.Modification")]
    [System.SerializableAttribute()]
    public partial class ProductRevisionEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ReleaseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short RevisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.ProductState StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReleaseDate {
            get {
                return this.ReleaseDateField;
            }
            set {
                if ((this.ReleaseDateField.Equals(value) != true)) {
                    this.ReleaseDateField = value;
                    this.RaisePropertyChanged("ReleaseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Revision {
            get {
                return this.RevisionField;
            }
            set {
                if ((this.RevisionField.Equals(value) != true)) {
                    this.RevisionField = value;
                    this.RaisePropertyChanged("Revision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.ProductState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkplanModel", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Products.Management.Modification", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class WorkplanModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Workflows.WorkplanState StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Workflows.WorkplanState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Version {
            get {
                return this.VersionField;
            }
            set {
                if ((this.VersionField.Equals(value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductService.IProductInteraction")]
    public interface IProductInteraction {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetCustomization", ReplyAction="http://tempuri.org/IProductInteraction/GetCustomizationResponse")]
        Marvin.Products.UI.ProductService.ProductCustomization GetCustomization();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetCustomization", ReplyAction="http://tempuri.org/IProductInteraction/GetCustomizationResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductCustomization> GetCustomizationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/UpdateParameters", ReplyAction="http://tempuri.org/IProductInteraction/UpdateParametersResponse")]
        Marvin.Serialization.Entry UpdateParameters(string importer, Marvin.Serialization.Entry currentParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/UpdateParameters", ReplyAction="http://tempuri.org/IProductInteraction/UpdateParametersResponse")]
        System.Threading.Tasks.Task<Marvin.Serialization.Entry> UpdateParametersAsync(string importer, Marvin.Serialization.Entry currentParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetProductStructure", ReplyAction="http://tempuri.org/IProductInteraction/GetProductStructureResponse")]
        Marvin.Products.UI.ProductService.ProductStructureEntry[] GetProductStructure();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetProductStructure", ReplyAction="http://tempuri.org/IProductInteraction/GetProductStructureResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductStructureEntry[]> GetProductStructureAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetAllProducts", ReplyAction="http://tempuri.org/IProductInteraction/GetAllProductsResponse")]
        Marvin.Products.UI.ProductService.ProductModel[] GetAllProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetAllProducts", ReplyAction="http://tempuri.org/IProductInteraction/GetAllProductsResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductModel[]> GetAllProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetProductDetails", ReplyAction="http://tempuri.org/IProductInteraction/GetProductDetailsResponse")]
        Marvin.Products.UI.ProductService.ProductModel GetProductDetails(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetProductDetails", ReplyAction="http://tempuri.org/IProductInteraction/GetProductDetailsResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductModel> GetProductDetailsAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetProductRevisions", ReplyAction="http://tempuri.org/IProductInteraction/GetProductRevisionsResponse")]
        Marvin.Products.UI.ProductService.ProductRevisionEntry[] GetProductRevisions(string identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetProductRevisions", ReplyAction="http://tempuri.org/IProductInteraction/GetProductRevisionsResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductRevisionEntry[]> GetProductRevisionsAsync(string identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/SaveProduct", ReplyAction="http://tempuri.org/IProductInteraction/SaveProductResponse")]
        Marvin.Products.UI.ProductService.ProductModel SaveProduct(Marvin.Products.UI.ProductService.ProductModel instance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/SaveProduct", ReplyAction="http://tempuri.org/IProductInteraction/SaveProductResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductModel> SaveProductAsync(Marvin.Products.UI.ProductService.ProductModel instance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/ReleaseProduct", ReplyAction="http://tempuri.org/IProductInteraction/ReleaseProductResponse")]
        Marvin.Products.UI.ProductService.ProductModel ReleaseProduct(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/ReleaseProduct", ReplyAction="http://tempuri.org/IProductInteraction/ReleaseProductResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductModel> ReleaseProductAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/CreateRevision", ReplyAction="http://tempuri.org/IProductInteraction/CreateRevisionResponse")]
        Marvin.Products.UI.ProductService.ProductModel CreateRevision(long id, short revisionNo, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/CreateRevision", ReplyAction="http://tempuri.org/IProductInteraction/CreateRevisionResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductModel> CreateRevisionAsync(long id, short revisionNo, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/ImportProduct", ReplyAction="http://tempuri.org/IProductInteraction/ImportProductResponse")]
        Marvin.Products.UI.ProductService.ProductModel ImportProduct(string importerName, Marvin.Serialization.Entry parametersModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/ImportProduct", ReplyAction="http://tempuri.org/IProductInteraction/ImportProductResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductModel> ImportProductAsync(string importerName, Marvin.Serialization.Entry parametersModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/DeleteProduct", ReplyAction="http://tempuri.org/IProductInteraction/DeleteProductResponse")]
        Marvin.Products.UI.ProductService.ProductModel[] DeleteProduct(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/DeleteProduct", ReplyAction="http://tempuri.org/IProductInteraction/DeleteProductResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductModel[]> DeleteProductAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetRecipe", ReplyAction="http://tempuri.org/IProductInteraction/GetRecipeResponse")]
        Marvin.Products.UI.ProductService.RecipeModel GetRecipe(long recipeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetRecipe", ReplyAction="http://tempuri.org/IProductInteraction/GetRecipeResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.RecipeModel> GetRecipeAsync(long recipeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetRecipes", ReplyAction="http://tempuri.org/IProductInteraction/GetRecipesResponse")]
        Marvin.Products.UI.ProductService.RecipeModel[] GetRecipes(long productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetRecipes", ReplyAction="http://tempuri.org/IProductInteraction/GetRecipesResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.RecipeModel[]> GetRecipesAsync(long productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/CreateRecipe", ReplyAction="http://tempuri.org/IProductInteraction/CreateRecipeResponse")]
        Marvin.Products.UI.ProductService.RecipeModel CreateRecipe(string recipeType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/CreateRecipe", ReplyAction="http://tempuri.org/IProductInteraction/CreateRecipeResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.RecipeModel> CreateRecipeAsync(string recipeType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetProductionRecipe", ReplyAction="http://tempuri.org/IProductInteraction/GetProductionRecipeResponse")]
        Marvin.Products.UI.ProductService.RecipeModel GetProductionRecipe(long productId, long workplanId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetProductionRecipe", ReplyAction="http://tempuri.org/IProductInteraction/GetProductionRecipeResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.RecipeModel> GetProductionRecipeAsync(long productId, long workplanId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/CreateProductionRecipe", ReplyAction="http://tempuri.org/IProductInteraction/CreateProductionRecipeResponse")]
        Marvin.Products.UI.ProductService.RecipeModel CreateProductionRecipe(long productId, long workplanId, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/CreateProductionRecipe", ReplyAction="http://tempuri.org/IProductInteraction/CreateProductionRecipeResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.RecipeModel> CreateProductionRecipeAsync(long productId, long workplanId, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/SaveProductionRecipe", ReplyAction="http://tempuri.org/IProductInteraction/SaveProductionRecipeResponse")]
        bool SaveProductionRecipe(Marvin.Products.UI.ProductService.RecipeModel recipe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/SaveProductionRecipe", ReplyAction="http://tempuri.org/IProductInteraction/SaveProductionRecipeResponse")]
        System.Threading.Tasks.Task<bool> SaveProductionRecipeAsync(Marvin.Products.UI.ProductService.RecipeModel recipe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/CreateWorkplan", ReplyAction="http://tempuri.org/IProductInteraction/CreateWorkplanResponse")]
        Marvin.Products.UI.ProductService.WorkplanModel CreateWorkplan(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/CreateWorkplan", ReplyAction="http://tempuri.org/IProductInteraction/CreateWorkplanResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.WorkplanModel> CreateWorkplanAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetWorkplans", ReplyAction="http://tempuri.org/IProductInteraction/GetWorkplansResponse")]
        Marvin.Products.UI.ProductService.WorkplanModel[] GetWorkplans();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetWorkplans", ReplyAction="http://tempuri.org/IProductInteraction/GetWorkplansResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.WorkplanModel[]> GetWorkplansAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetWorkplan", ReplyAction="http://tempuri.org/IProductInteraction/GetWorkplanResponse")]
        Marvin.Products.UI.ProductService.WorkplanModel GetWorkplan(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetWorkplan", ReplyAction="http://tempuri.org/IProductInteraction/GetWorkplanResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.WorkplanModel> GetWorkplanAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetRecipeProviderName", ReplyAction="http://tempuri.org/IProductInteraction/GetRecipeProviderNameResponse")]
        string GetRecipeProviderName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetRecipeProviderName", ReplyAction="http://tempuri.org/IProductInteraction/GetRecipeProviderNameResponse")]
        System.Threading.Tasks.Task<string> GetRecipeProviderNameAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductInteractionChannel : Marvin.Products.UI.ProductService.IProductInteraction, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductInteractionClient : System.ServiceModel.ClientBase<Marvin.Products.UI.ProductService.IProductInteraction>, Marvin.Products.UI.ProductService.IProductInteraction {
        
        public ProductInteractionClient() {
        }
        
        public ProductInteractionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductInteractionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductInteractionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductInteractionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Marvin.Products.UI.ProductService.ProductCustomization GetCustomization() {
            return base.Channel.GetCustomization();
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductCustomization> GetCustomizationAsync() {
            return base.Channel.GetCustomizationAsync();
        }
        
        public Marvin.Serialization.Entry UpdateParameters(string importer, Marvin.Serialization.Entry currentParameters) {
            return base.Channel.UpdateParameters(importer, currentParameters);
        }
        
        public System.Threading.Tasks.Task<Marvin.Serialization.Entry> UpdateParametersAsync(string importer, Marvin.Serialization.Entry currentParameters) {
            return base.Channel.UpdateParametersAsync(importer, currentParameters);
        }
        
        public Marvin.Products.UI.ProductService.ProductStructureEntry[] GetProductStructure() {
            return base.Channel.GetProductStructure();
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductStructureEntry[]> GetProductStructureAsync() {
            return base.Channel.GetProductStructureAsync();
        }
        
        public Marvin.Products.UI.ProductService.ProductModel[] GetAllProducts() {
            return base.Channel.GetAllProducts();
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductModel[]> GetAllProductsAsync() {
            return base.Channel.GetAllProductsAsync();
        }
        
        public Marvin.Products.UI.ProductService.ProductModel GetProductDetails(long id) {
            return base.Channel.GetProductDetails(id);
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductModel> GetProductDetailsAsync(long id) {
            return base.Channel.GetProductDetailsAsync(id);
        }
        
        public Marvin.Products.UI.ProductService.ProductRevisionEntry[] GetProductRevisions(string identifier) {
            return base.Channel.GetProductRevisions(identifier);
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductRevisionEntry[]> GetProductRevisionsAsync(string identifier) {
            return base.Channel.GetProductRevisionsAsync(identifier);
        }
        
        public Marvin.Products.UI.ProductService.ProductModel SaveProduct(Marvin.Products.UI.ProductService.ProductModel instance) {
            return base.Channel.SaveProduct(instance);
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductModel> SaveProductAsync(Marvin.Products.UI.ProductService.ProductModel instance) {
            return base.Channel.SaveProductAsync(instance);
        }
        
        public Marvin.Products.UI.ProductService.ProductModel ReleaseProduct(long id) {
            return base.Channel.ReleaseProduct(id);
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductModel> ReleaseProductAsync(long id) {
            return base.Channel.ReleaseProductAsync(id);
        }
        
        public Marvin.Products.UI.ProductService.ProductModel CreateRevision(long id, short revisionNo, string comment) {
            return base.Channel.CreateRevision(id, revisionNo, comment);
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductModel> CreateRevisionAsync(long id, short revisionNo, string comment) {
            return base.Channel.CreateRevisionAsync(id, revisionNo, comment);
        }
        
        public Marvin.Products.UI.ProductService.ProductModel ImportProduct(string importerName, Marvin.Serialization.Entry parametersModel) {
            return base.Channel.ImportProduct(importerName, parametersModel);
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductModel> ImportProductAsync(string importerName, Marvin.Serialization.Entry parametersModel) {
            return base.Channel.ImportProductAsync(importerName, parametersModel);
        }
        
        public Marvin.Products.UI.ProductService.ProductModel[] DeleteProduct(long id) {
            return base.Channel.DeleteProduct(id);
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductModel[]> DeleteProductAsync(long id) {
            return base.Channel.DeleteProductAsync(id);
        }
        
        public Marvin.Products.UI.ProductService.RecipeModel GetRecipe(long recipeId) {
            return base.Channel.GetRecipe(recipeId);
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.RecipeModel> GetRecipeAsync(long recipeId) {
            return base.Channel.GetRecipeAsync(recipeId);
        }
        
        public Marvin.Products.UI.ProductService.RecipeModel[] GetRecipes(long productId) {
            return base.Channel.GetRecipes(productId);
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.RecipeModel[]> GetRecipesAsync(long productId) {
            return base.Channel.GetRecipesAsync(productId);
        }
        
        public Marvin.Products.UI.ProductService.RecipeModel CreateRecipe(string recipeType) {
            return base.Channel.CreateRecipe(recipeType);
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.RecipeModel> CreateRecipeAsync(string recipeType) {
            return base.Channel.CreateRecipeAsync(recipeType);
        }
        
        public Marvin.Products.UI.ProductService.RecipeModel GetProductionRecipe(long productId, long workplanId) {
            return base.Channel.GetProductionRecipe(productId, workplanId);
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.RecipeModel> GetProductionRecipeAsync(long productId, long workplanId) {
            return base.Channel.GetProductionRecipeAsync(productId, workplanId);
        }
        
        public Marvin.Products.UI.ProductService.RecipeModel CreateProductionRecipe(long productId, long workplanId, string name) {
            return base.Channel.CreateProductionRecipe(productId, workplanId, name);
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.RecipeModel> CreateProductionRecipeAsync(long productId, long workplanId, string name) {
            return base.Channel.CreateProductionRecipeAsync(productId, workplanId, name);
        }
        
        public bool SaveProductionRecipe(Marvin.Products.UI.ProductService.RecipeModel recipe) {
            return base.Channel.SaveProductionRecipe(recipe);
        }
        
        public System.Threading.Tasks.Task<bool> SaveProductionRecipeAsync(Marvin.Products.UI.ProductService.RecipeModel recipe) {
            return base.Channel.SaveProductionRecipeAsync(recipe);
        }
        
        public Marvin.Products.UI.ProductService.WorkplanModel CreateWorkplan(string name) {
            return base.Channel.CreateWorkplan(name);
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.WorkplanModel> CreateWorkplanAsync(string name) {
            return base.Channel.CreateWorkplanAsync(name);
        }
        
        public Marvin.Products.UI.ProductService.WorkplanModel[] GetWorkplans() {
            return base.Channel.GetWorkplans();
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.WorkplanModel[]> GetWorkplansAsync() {
            return base.Channel.GetWorkplansAsync();
        }
        
        public Marvin.Products.UI.ProductService.WorkplanModel GetWorkplan(long id) {
            return base.Channel.GetWorkplan(id);
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.WorkplanModel> GetWorkplanAsync(long id) {
            return base.Channel.GetWorkplanAsync(id);
        }
        
        public string GetRecipeProviderName() {
            return base.Channel.GetRecipeProviderName();
        }
        
        public System.Threading.Tasks.Task<string> GetRecipeProviderNameAsync() {
            return base.Channel.GetRecipeProviderNameAsync();
        }
    }
}
