// Copyright (c) 2020, Phoenix Contact GmbH & Co. KG
// Licensed under the Apache License, Version 2.0

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marvin.Products.UI.ProductService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductCustomization", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Products.Management.Modification")]
    [System.SerializableAttribute()]
    public partial class ProductCustomization : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.ProductImporter[] ImportersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.ProductTypeModel[] ProductTypesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.RecipeTypeModel[] RecipeTypesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.ProductImporter[] Importers {
            get {
                return this.ImportersField;
            }
            set {
                if ((object.ReferenceEquals(this.ImportersField, value) != true)) {
                    this.ImportersField = value;
                    this.RaisePropertyChanged("Importers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.ProductTypeModel[] ProductTypes {
            get {
                return this.ProductTypesField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductTypesField, value) != true)) {
                    this.ProductTypesField = value;
                    this.RaisePropertyChanged("ProductTypes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.RecipeTypeModel[] RecipeTypes {
            get {
                return this.RecipeTypesField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipeTypesField, value) != true)) {
                    this.RecipeTypesField = value;
                    this.RaisePropertyChanged("RecipeTypes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductImporter", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Products.Management.Modification")]
    [System.SerializableAttribute()]
    public partial class ProductImporter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Serialization.Entry ParametersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Serialization.Entry Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductTypeModel", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Products.Management.Modification")]
    [System.SerializableAttribute()]
    public partial class ProductTypeModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BaseTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BaseType {
            get {
                return this.BaseTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.BaseTypeField, value) != true)) {
                    this.BaseTypeField = value;
                    this.RaisePropertyChanged("BaseType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecipeTypeModel", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Products.Management.Modification")]
    [System.SerializableAttribute()]
    public partial class RecipeTypeModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasWorkplansField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasWorkplans {
            get {
                return this.HasWorkplansField;
            }
            set {
                if ((this.HasWorkplansField.Equals(value) != true)) {
                    this.HasWorkplansField = value;
                    this.RaisePropertyChanged("HasWorkplans");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductQuery", Namespace="http://schemas.datacontract.org/2004/07/Marvin.AbstractionLayer")]
    [System.SerializableAttribute()]
    public partial class ProductQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExcludeDerivedTypesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IncludeDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.RecipeFilter RecipeFilterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short RevisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.RevisionFilter RevisionFilterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.Selector SelectorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ExcludeDerivedTypes {
            get {
                return this.ExcludeDerivedTypesField;
            }
            set {
                if ((this.ExcludeDerivedTypesField.Equals(value) != true)) {
                    this.ExcludeDerivedTypesField = value;
                    this.RaisePropertyChanged("ExcludeDerivedTypes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identifier {
            get {
                return this.IdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentifierField, value) != true)) {
                    this.IdentifierField = value;
                    this.RaisePropertyChanged("Identifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeDeleted {
            get {
                return this.IncludeDeletedField;
            }
            set {
                if ((this.IncludeDeletedField.Equals(value) != true)) {
                    this.IncludeDeletedField = value;
                    this.RaisePropertyChanged("IncludeDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.RecipeFilter RecipeFilter {
            get {
                return this.RecipeFilterField;
            }
            set {
                if ((this.RecipeFilterField.Equals(value) != true)) {
                    this.RecipeFilterField = value;
                    this.RaisePropertyChanged("RecipeFilter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Revision {
            get {
                return this.RevisionField;
            }
            set {
                if ((this.RevisionField.Equals(value) != true)) {
                    this.RevisionField = value;
                    this.RaisePropertyChanged("Revision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.RevisionFilter RevisionFilter {
            get {
                return this.RevisionFilterField;
            }
            set {
                if ((this.RevisionFilterField.Equals(value) != true)) {
                    this.RevisionFilterField = value;
                    this.RaisePropertyChanged("RevisionFilter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.Selector Selector {
            get {
                return this.SelectorField;
            }
            set {
                if ((this.SelectorField.Equals(value) != true)) {
                    this.SelectorField = value;
                    this.RaisePropertyChanged("Selector");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecipeFilter", Namespace="http://schemas.datacontract.org/2004/07/Marvin.AbstractionLayer")]
    public enum RecipeFilter : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unset = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WithRecipe = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WithoutRecipes = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RevisionFilter", Namespace="http://schemas.datacontract.org/2004/07/Marvin.AbstractionLayer")]
    public enum RevisionFilter : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Latest = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Specific = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Selector", Namespace="http://schemas.datacontract.org/2004/07/Marvin.AbstractionLayer")]
    public enum Selector : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Direct = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Parent = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Parts = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductModel", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Products.Management.Modification", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ProductModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.ProductFile[] FilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.PartConnector[] PartsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Serialization.Entry PropertiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.RecipeModel[] RecipesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short RevisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.ProductTypeState StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.ProductFile[] Files {
            get {
                return this.FilesField;
            }
            set {
                if ((object.ReferenceEquals(this.FilesField, value) != true)) {
                    this.FilesField = value;
                    this.RaisePropertyChanged("Files");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identifier {
            get {
                return this.IdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentifierField, value) != true)) {
                    this.IdentifierField = value;
                    this.RaisePropertyChanged("Identifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.PartConnector[] Parts {
            get {
                return this.PartsField;
            }
            set {
                if ((object.ReferenceEquals(this.PartsField, value) != true)) {
                    this.PartsField = value;
                    this.RaisePropertyChanged("Parts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Serialization.Entry Properties {
            get {
                return this.PropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertiesField, value) != true)) {
                    this.PropertiesField = value;
                    this.RaisePropertyChanged("Properties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.RecipeModel[] Recipes {
            get {
                return this.RecipesField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipesField, value) != true)) {
                    this.RecipesField = value;
                    this.RaisePropertyChanged("Recipes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Revision {
            get {
                return this.RevisionField;
            }
            set {
                if ((this.RevisionField.Equals(value) != true)) {
                    this.RevisionField = value;
                    this.RaisePropertyChanged("Revision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.ProductTypeState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductFile", Namespace="http://schemas.datacontract.org/2004/07/Marvin.AbstractionLayer")]
    [System.SerializableAttribute()]
    public partial class ProductFile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MimeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileHash {
            get {
                return this.FileHashField;
            }
            set {
                if ((object.ReferenceEquals(this.FileHashField, value) != true)) {
                    this.FileHashField = value;
                    this.RaisePropertyChanged("FileHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilePath {
            get {
                return this.FilePathField;
            }
            set {
                if ((object.ReferenceEquals(this.FilePathField, value) != true)) {
                    this.FilePathField = value;
                    this.RaisePropertyChanged("FilePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MimeType {
            get {
                return this.MimeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MimeTypeField, value) != true)) {
                    this.MimeTypeField = value;
                    this.RaisePropertyChanged("MimeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartConnector", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Products.Management.Modification", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class PartConnector : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCollectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.PartModel[] PartsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Serialization.Entry PropertyTemplatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCollection {
            get {
                return this.IsCollectionField;
            }
            set {
                if ((this.IsCollectionField.Equals(value) != true)) {
                    this.IsCollectionField = value;
                    this.RaisePropertyChanged("IsCollection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.PartModel[] Parts {
            get {
                return this.PartsField;
            }
            set {
                if ((object.ReferenceEquals(this.PartsField, value) != true)) {
                    this.PartsField = value;
                    this.RaisePropertyChanged("Parts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Serialization.Entry PropertyTemplates {
            get {
                return this.PropertyTemplatesField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyTemplatesField, value) != true)) {
                    this.PropertyTemplatesField = value;
                    this.RaisePropertyChanged("PropertyTemplates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecipeModel", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Products.Management.Modification", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class RecipeModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.RecipeClassificationModel ClassificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Serialization.Entry PropertiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RevisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.RecipeState StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long WorkplanIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.RecipeClassificationModel Classification {
            get {
                return this.ClassificationField;
            }
            set {
                if ((this.ClassificationField.Equals(value) != true)) {
                    this.ClassificationField = value;
                    this.RaisePropertyChanged("Classification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Serialization.Entry Properties {
            get {
                return this.PropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertiesField, value) != true)) {
                    this.PropertiesField = value;
                    this.RaisePropertyChanged("Properties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Revision {
            get {
                return this.RevisionField;
            }
            set {
                if ((this.RevisionField.Equals(value) != true)) {
                    this.RevisionField = value;
                    this.RaisePropertyChanged("Revision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.RecipeState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long WorkplanId {
            get {
                return this.WorkplanIdField;
            }
            set {
                if ((this.WorkplanIdField.Equals(value) != true)) {
                    this.WorkplanIdField = value;
                    this.RaisePropertyChanged("WorkplanId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductTypeState", Namespace="http://schemas.datacontract.org/2004/07/Marvin.AbstractionLayer")]
    public enum ProductTypeState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Created = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Released = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deprecated = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartModel", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Products.Management.Modification", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class PartModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.ProductModel ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Serialization.Entry PropertiesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.ProductModel Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Serialization.Entry Properties {
            get {
                return this.PropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertiesField, value) != true)) {
                    this.PropertiesField = value;
                    this.RaisePropertyChanged("Properties");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecipeClassificationModel", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Products.Management.Modification")]
    public enum RecipeClassificationModel : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unset = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Default = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Alternative = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Intermediate = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Part = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecipeState", Namespace="http://schemas.datacontract.org/2004/07/Marvin.AbstractionLayer")]
    public enum RecipeState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        New = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Released = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Revoked = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DuplicateProductResponse", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Products.Management.Modification")]
    [System.SerializableAttribute()]
    public partial class DuplicateProductResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Products.UI.ProductService.ProductModel DuplicateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IdentityConflictField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InvalidSourceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Products.UI.ProductService.ProductModel Duplicate {
            get {
                return this.DuplicateField;
            }
            set {
                if ((object.ReferenceEquals(this.DuplicateField, value) != true)) {
                    this.DuplicateField = value;
                    this.RaisePropertyChanged("Duplicate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IdentityConflict {
            get {
                return this.IdentityConflictField;
            }
            set {
                if ((this.IdentityConflictField.Equals(value) != true)) {
                    this.IdentityConflictField = value;
                    this.RaisePropertyChanged("IdentityConflict");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InvalidSource {
            get {
                return this.InvalidSourceField;
            }
            set {
                if ((this.InvalidSourceField.Equals(value) != true)) {
                    this.InvalidSourceField = value;
                    this.RaisePropertyChanged("InvalidSource");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkplanModel", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Products.Management.Modification", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class WorkplanModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Workflows.WorkplanState StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Workflows.WorkplanState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Version {
            get {
                return this.VersionField;
            }
            set {
                if ((this.VersionField.Equals(value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductService.IProductInteraction")]
    public interface IProductInteraction {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetCustomization", ReplyAction="http://tempuri.org/IProductInteraction/GetCustomizationResponse")]
        Marvin.Products.UI.ProductService.ProductCustomization GetCustomization();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetCustomization", ReplyAction="http://tempuri.org/IProductInteraction/GetCustomizationResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductCustomization> GetCustomizationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetProducts", ReplyAction="http://tempuri.org/IProductInteraction/GetProductsResponse")]
        Marvin.Products.UI.ProductService.ProductModel[] GetProducts(Marvin.Products.UI.ProductService.ProductQuery query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetProducts", ReplyAction="http://tempuri.org/IProductInteraction/GetProductsResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductModel[]> GetProductsAsync(Marvin.Products.UI.ProductService.ProductQuery query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/CreateProduct", ReplyAction="http://tempuri.org/IProductInteraction/CreateProductResponse")]
        Marvin.Products.UI.ProductService.ProductModel CreateProduct(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/CreateProduct", ReplyAction="http://tempuri.org/IProductInteraction/CreateProductResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductModel> CreateProductAsync(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetProductDetails", ReplyAction="http://tempuri.org/IProductInteraction/GetProductDetailsResponse")]
        Marvin.Products.UI.ProductService.ProductModel GetProductDetails(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetProductDetails", ReplyAction="http://tempuri.org/IProductInteraction/GetProductDetailsResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductModel> GetProductDetailsAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/SaveProduct", ReplyAction="http://tempuri.org/IProductInteraction/SaveProductResponse")]
        Marvin.Products.UI.ProductService.ProductModel SaveProduct(Marvin.Products.UI.ProductService.ProductModel instance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/SaveProduct", ReplyAction="http://tempuri.org/IProductInteraction/SaveProductResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductModel> SaveProductAsync(Marvin.Products.UI.ProductService.ProductModel instance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/DuplicateProduct", ReplyAction="http://tempuri.org/IProductInteraction/DuplicateProductResponse")]
        Marvin.Products.UI.ProductService.DuplicateProductResponse DuplicateProduct(long sourceId, string identifier, short revisionNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/DuplicateProduct", ReplyAction="http://tempuri.org/IProductInteraction/DuplicateProductResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.DuplicateProductResponse> DuplicateProductAsync(long sourceId, string identifier, short revisionNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/DeleteProduct", ReplyAction="http://tempuri.org/IProductInteraction/DeleteProductResponse")]
        bool DeleteProduct(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/DeleteProduct", ReplyAction="http://tempuri.org/IProductInteraction/DeleteProductResponse")]
        System.Threading.Tasks.Task<bool> DeleteProductAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/ImportProduct", ReplyAction="http://tempuri.org/IProductInteraction/ImportProductResponse")]
        Marvin.Products.UI.ProductService.ProductModel ImportProduct(string importerName, Marvin.Serialization.Entry parametersModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/ImportProduct", ReplyAction="http://tempuri.org/IProductInteraction/ImportProductResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductModel> ImportProductAsync(string importerName, Marvin.Serialization.Entry parametersModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/UpdateParameters", ReplyAction="http://tempuri.org/IProductInteraction/UpdateParametersResponse")]
        Marvin.Serialization.Entry UpdateParameters(string importer, Marvin.Serialization.Entry currentParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/UpdateParameters", ReplyAction="http://tempuri.org/IProductInteraction/UpdateParametersResponse")]
        System.Threading.Tasks.Task<Marvin.Serialization.Entry> UpdateParametersAsync(string importer, Marvin.Serialization.Entry currentParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetRecipe", ReplyAction="http://tempuri.org/IProductInteraction/GetRecipeResponse")]
        Marvin.Products.UI.ProductService.RecipeModel GetRecipe(long recipeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetRecipe", ReplyAction="http://tempuri.org/IProductInteraction/GetRecipeResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.RecipeModel> GetRecipeAsync(long recipeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetRecipes", ReplyAction="http://tempuri.org/IProductInteraction/GetRecipesResponse")]
        Marvin.Products.UI.ProductService.RecipeModel[] GetRecipes(long productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetRecipes", ReplyAction="http://tempuri.org/IProductInteraction/GetRecipesResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.RecipeModel[]> GetRecipesAsync(long productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/CreateRecipe", ReplyAction="http://tempuri.org/IProductInteraction/CreateRecipeResponse")]
        Marvin.Products.UI.ProductService.RecipeModel CreateRecipe(string recipeType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/CreateRecipe", ReplyAction="http://tempuri.org/IProductInteraction/CreateRecipeResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.RecipeModel> CreateRecipeAsync(string recipeType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/SaveRecipe", ReplyAction="http://tempuri.org/IProductInteraction/SaveRecipeResponse")]
        Marvin.Products.UI.ProductService.RecipeModel SaveRecipe(Marvin.Products.UI.ProductService.RecipeModel recipe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/SaveRecipe", ReplyAction="http://tempuri.org/IProductInteraction/SaveRecipeResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.RecipeModel> SaveRecipeAsync(Marvin.Products.UI.ProductService.RecipeModel recipe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetWorkplans", ReplyAction="http://tempuri.org/IProductInteraction/GetWorkplansResponse")]
        Marvin.Products.UI.ProductService.WorkplanModel[] GetWorkplans();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetWorkplans", ReplyAction="http://tempuri.org/IProductInteraction/GetWorkplansResponse")]
        System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.WorkplanModel[]> GetWorkplansAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetRecipeProviderName", ReplyAction="http://tempuri.org/IProductInteraction/GetRecipeProviderNameResponse")]
        string GetRecipeProviderName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductInteraction/GetRecipeProviderName", ReplyAction="http://tempuri.org/IProductInteraction/GetRecipeProviderNameResponse")]
        System.Threading.Tasks.Task<string> GetRecipeProviderNameAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductInteractionChannel : Marvin.Products.UI.ProductService.IProductInteraction, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductInteractionClient : System.ServiceModel.ClientBase<Marvin.Products.UI.ProductService.IProductInteraction>, Marvin.Products.UI.ProductService.IProductInteraction {
        
        public ProductInteractionClient() {
        }
        
        public ProductInteractionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductInteractionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductInteractionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductInteractionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Marvin.Products.UI.ProductService.ProductCustomization GetCustomization() {
            return base.Channel.GetCustomization();
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductCustomization> GetCustomizationAsync() {
            return base.Channel.GetCustomizationAsync();
        }
        
        public Marvin.Products.UI.ProductService.ProductModel[] GetProducts(Marvin.Products.UI.ProductService.ProductQuery query) {
            return base.Channel.GetProducts(query);
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductModel[]> GetProductsAsync(Marvin.Products.UI.ProductService.ProductQuery query) {
            return base.Channel.GetProductsAsync(query);
        }
        
        public Marvin.Products.UI.ProductService.ProductModel CreateProduct(string type) {
            return base.Channel.CreateProduct(type);
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductModel> CreateProductAsync(string type) {
            return base.Channel.CreateProductAsync(type);
        }
        
        public Marvin.Products.UI.ProductService.ProductModel GetProductDetails(long id) {
            return base.Channel.GetProductDetails(id);
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductModel> GetProductDetailsAsync(long id) {
            return base.Channel.GetProductDetailsAsync(id);
        }
        
        public Marvin.Products.UI.ProductService.ProductModel SaveProduct(Marvin.Products.UI.ProductService.ProductModel instance) {
            return base.Channel.SaveProduct(instance);
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductModel> SaveProductAsync(Marvin.Products.UI.ProductService.ProductModel instance) {
            return base.Channel.SaveProductAsync(instance);
        }
        
        public Marvin.Products.UI.ProductService.DuplicateProductResponse DuplicateProduct(long sourceId, string identifier, short revisionNo) {
            return base.Channel.DuplicateProduct(sourceId, identifier, revisionNo);
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.DuplicateProductResponse> DuplicateProductAsync(long sourceId, string identifier, short revisionNo) {
            return base.Channel.DuplicateProductAsync(sourceId, identifier, revisionNo);
        }
        
        public bool DeleteProduct(long id) {
            return base.Channel.DeleteProduct(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteProductAsync(long id) {
            return base.Channel.DeleteProductAsync(id);
        }
        
        public Marvin.Products.UI.ProductService.ProductModel ImportProduct(string importerName, Marvin.Serialization.Entry parametersModel) {
            return base.Channel.ImportProduct(importerName, parametersModel);
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.ProductModel> ImportProductAsync(string importerName, Marvin.Serialization.Entry parametersModel) {
            return base.Channel.ImportProductAsync(importerName, parametersModel);
        }
        
        public Marvin.Serialization.Entry UpdateParameters(string importer, Marvin.Serialization.Entry currentParameters) {
            return base.Channel.UpdateParameters(importer, currentParameters);
        }
        
        public System.Threading.Tasks.Task<Marvin.Serialization.Entry> UpdateParametersAsync(string importer, Marvin.Serialization.Entry currentParameters) {
            return base.Channel.UpdateParametersAsync(importer, currentParameters);
        }
        
        public Marvin.Products.UI.ProductService.RecipeModel GetRecipe(long recipeId) {
            return base.Channel.GetRecipe(recipeId);
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.RecipeModel> GetRecipeAsync(long recipeId) {
            return base.Channel.GetRecipeAsync(recipeId);
        }
        
        public Marvin.Products.UI.ProductService.RecipeModel[] GetRecipes(long productId) {
            return base.Channel.GetRecipes(productId);
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.RecipeModel[]> GetRecipesAsync(long productId) {
            return base.Channel.GetRecipesAsync(productId);
        }
        
        public Marvin.Products.UI.ProductService.RecipeModel CreateRecipe(string recipeType) {
            return base.Channel.CreateRecipe(recipeType);
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.RecipeModel> CreateRecipeAsync(string recipeType) {
            return base.Channel.CreateRecipeAsync(recipeType);
        }
        
        public Marvin.Products.UI.ProductService.RecipeModel SaveRecipe(Marvin.Products.UI.ProductService.RecipeModel recipe) {
            return base.Channel.SaveRecipe(recipe);
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.RecipeModel> SaveRecipeAsync(Marvin.Products.UI.ProductService.RecipeModel recipe) {
            return base.Channel.SaveRecipeAsync(recipe);
        }
        
        public Marvin.Products.UI.ProductService.WorkplanModel[] GetWorkplans() {
            return base.Channel.GetWorkplans();
        }
        
        public System.Threading.Tasks.Task<Marvin.Products.UI.ProductService.WorkplanModel[]> GetWorkplansAsync() {
            return base.Channel.GetWorkplansAsync();
        }
        
        public string GetRecipeProviderName() {
            return base.Channel.GetRecipeProviderName();
        }
        
        public System.Threading.Tasks.Task<string> GetRecipeProviderNameAsync() {
            return base.Channel.GetRecipeProviderNameAsync();
        }
    }
}
