//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moryx.Products.UI.ProductService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductCustomization", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Products.Management.Modification")]
    public partial class ProductCustomization : object
    {
        
        private Moryx.Products.UI.ProductService.ProductImporter[] ImportersField;
        
        private Moryx.Products.UI.ProductService.ProductDefinitionModel[] ProductTypesField;
        
        private Moryx.Products.UI.ProductService.RecipeDefinitionModel[] RecipeTypesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Products.UI.ProductService.ProductImporter[] Importers
        {
            get
            {
                return this.ImportersField;
            }
            set
            {
                this.ImportersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Products.UI.ProductService.ProductDefinitionModel[] ProductTypes
        {
            get
            {
                return this.ProductTypesField;
            }
            set
            {
                this.ProductTypesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Products.UI.ProductService.RecipeDefinitionModel[] RecipeTypes
        {
            get
            {
                return this.RecipeTypesField;
            }
            set
            {
                this.RecipeTypesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductImporter", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Products.Management.Modification")]
    public partial class ProductImporter : object
    {
        
        private string NameField;
        
        private Moryx.Products.UI.ProductService.Entry ParametersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Products.UI.ProductService.Entry Parameters
        {
            get
            {
                return this.ParametersField;
            }
            set
            {
                this.ParametersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDefinitionModel", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Products.Management.Modification")]
    public partial class ProductDefinitionModel : object
    {
        
        private string BaseDefinitionField;
        
        private string DisplayNameField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BaseDefinition
        {
            get
            {
                return this.BaseDefinitionField;
            }
            set
            {
                this.BaseDefinitionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName
        {
            get
            {
                return this.DisplayNameField;
            }
            set
            {
                this.DisplayNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecipeDefinitionModel", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Products.Management.Modification")]
    public partial class RecipeDefinitionModel : object
    {
        
        private string DisplayNameField;
        
        private bool HasWorkplansField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName
        {
            get
            {
                return this.DisplayNameField;
            }
            set
            {
                this.DisplayNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasWorkplans
        {
            get
            {
                return this.HasWorkplansField;
            }
            set
            {
                this.HasWorkplansField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entry", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Serialization")]
    public partial class Entry : object
    {
        
        private string DescriptionField;
        
        private string DisplayNameField;
        
        private string IdentifierField;
        
        private Moryx.Products.UI.ProductService.Entry[] PrototypesField;
        
        private Moryx.Products.UI.ProductService.Entry[] SubEntriesField;
        
        private Moryx.Products.UI.ProductService.EntryValidation ValidationField;
        
        private Moryx.Products.UI.ProductService.EntryValue ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName
        {
            get
            {
                return this.DisplayNameField;
            }
            set
            {
                this.DisplayNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identifier
        {
            get
            {
                return this.IdentifierField;
            }
            set
            {
                this.IdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Products.UI.ProductService.Entry[] Prototypes
        {
            get
            {
                return this.PrototypesField;
            }
            set
            {
                this.PrototypesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Products.UI.ProductService.Entry[] SubEntries
        {
            get
            {
                return this.SubEntriesField;
            }
            set
            {
                this.SubEntriesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Products.UI.ProductService.EntryValidation Validation
        {
            get
            {
                return this.ValidationField;
            }
            set
            {
                this.ValidationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Products.UI.ProductService.EntryValue Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntryValidation", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Serialization")]
    public partial class EntryValidation : object
    {
        
        private bool IsRequiredField;
        
        private double MaximumField;
        
        private double MinimumField;
        
        private string RegexField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRequired
        {
            get
            {
                return this.IsRequiredField;
            }
            set
            {
                this.IsRequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Maximum
        {
            get
            {
                return this.MaximumField;
            }
            set
            {
                this.MaximumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Minimum
        {
            get
            {
                return this.MinimumField;
            }
            set
            {
                this.MinimumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Regex
        {
            get
            {
                return this.RegexField;
            }
            set
            {
                this.RegexField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntryValue", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Serialization")]
    public partial class EntryValue : object
    {
        
        private string CurrentField;
        
        private string DefaultField;
        
        private bool IsReadOnlyField;
        
        private string[] PossibleField;
        
        private Moryx.Products.UI.ProductService.EntryValueType TypeField;
        
        private Moryx.Products.UI.ProductService.EntryUnitType UnitTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Current
        {
            get
            {
                return this.CurrentField;
            }
            set
            {
                this.CurrentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Default
        {
            get
            {
                return this.DefaultField;
            }
            set
            {
                this.DefaultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsReadOnly
        {
            get
            {
                return this.IsReadOnlyField;
            }
            set
            {
                this.IsReadOnlyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Possible
        {
            get
            {
                return this.PossibleField;
            }
            set
            {
                this.PossibleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Products.UI.ProductService.EntryValueType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Products.UI.ProductService.EntryUnitType UnitType
        {
            get
            {
                return this.UnitTypeField;
            }
            set
            {
                this.UnitTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntryValueType", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Serialization")]
    public enum EntryValueType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Byte = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Boolean = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Int16 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UInt16 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Int32 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UInt32 = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Int64 = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UInt64 = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Single = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Double = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        String = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Enum = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Class = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Collection = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exception = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Stream = 15,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntryUnitType", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Serialization")]
    public enum EntryUnitType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Password = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        File = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Directory = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductQuery", Namespace="http://schemas.datacontract.org/2004/07/Moryx.AbstractionLayer.Products")]
    public partial class ProductQuery : object
    {
        
        private bool ExcludeDerivedTypesField;
        
        private string IdentifierField;
        
        private bool IncludeDeletedField;
        
        private string NameField;
        
        private Moryx.Products.UI.ProductService.RecipeFilter RecipeFilterField;
        
        private short RevisionField;
        
        private Moryx.Products.UI.ProductService.RevisionFilter RevisionFilterField;
        
        private Moryx.Products.UI.ProductService.Selector SelectorField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ExcludeDerivedTypes
        {
            get
            {
                return this.ExcludeDerivedTypesField;
            }
            set
            {
                this.ExcludeDerivedTypesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identifier
        {
            get
            {
                return this.IdentifierField;
            }
            set
            {
                this.IdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeDeleted
        {
            get
            {
                return this.IncludeDeletedField;
            }
            set
            {
                this.IncludeDeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Products.UI.ProductService.RecipeFilter RecipeFilter
        {
            get
            {
                return this.RecipeFilterField;
            }
            set
            {
                this.RecipeFilterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Revision
        {
            get
            {
                return this.RevisionField;
            }
            set
            {
                this.RevisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Products.UI.ProductService.RevisionFilter RevisionFilter
        {
            get
            {
                return this.RevisionFilterField;
            }
            set
            {
                this.RevisionFilterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Products.UI.ProductService.Selector Selector
        {
            get
            {
                return this.SelectorField;
            }
            set
            {
                this.SelectorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecipeFilter", Namespace="http://schemas.datacontract.org/2004/07/Moryx.AbstractionLayer.Products")]
    public enum RecipeFilter : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unset = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WithRecipe = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WithoutRecipes = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RevisionFilter", Namespace="http://schemas.datacontract.org/2004/07/Moryx.AbstractionLayer.Products")]
    public enum RevisionFilter : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Latest = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Specific = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Selector", Namespace="http://schemas.datacontract.org/2004/07/Moryx.AbstractionLayer.Products")]
    public enum Selector : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Direct = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Parent = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Parts = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductModel", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Products.Management.Modification")]
    public partial class ProductModel : object
    {
        
        private Moryx.Products.UI.ProductService.ProductFile[] FilesField;
        
        private long IdField;
        
        private string IdentifierField;
        
        private string NameField;
        
        private Moryx.Products.UI.ProductService.PartConnector[] PartsField;
        
        private Moryx.Products.UI.ProductService.Entry PropertiesField;
        
        private Moryx.Products.UI.ProductService.RecipeModel[] RecipesField;
        
        private short RevisionField;
        
        private Moryx.Products.UI.ProductService.ProductState StateField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Products.UI.ProductService.ProductFile[] Files
        {
            get
            {
                return this.FilesField;
            }
            set
            {
                this.FilesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identifier
        {
            get
            {
                return this.IdentifierField;
            }
            set
            {
                this.IdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Products.UI.ProductService.PartConnector[] Parts
        {
            get
            {
                return this.PartsField;
            }
            set
            {
                this.PartsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Products.UI.ProductService.Entry Properties
        {
            get
            {
                return this.PropertiesField;
            }
            set
            {
                this.PropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Products.UI.ProductService.RecipeModel[] Recipes
        {
            get
            {
                return this.RecipesField;
            }
            set
            {
                this.RecipesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Revision
        {
            get
            {
                return this.RevisionField;
            }
            set
            {
                this.RevisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Products.UI.ProductService.ProductState State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductFile", Namespace="http://schemas.datacontract.org/2004/07/Moryx.AbstractionLayer.Products")]
    public partial class ProductFile : object
    {
        
        private string FileHashField;
        
        private string FilePathField;
        
        private string MimeTypeField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileHash
        {
            get
            {
                return this.FileHashField;
            }
            set
            {
                this.FileHashField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilePath
        {
            get
            {
                return this.FilePathField;
            }
            set
            {
                this.FilePathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MimeType
        {
            get
            {
                return this.MimeTypeField;
            }
            set
            {
                this.MimeTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartConnector", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Products.Management.Modification")]
    public partial class PartConnector : object
    {
        
        private string DisplayNameField;
        
        private bool IsCollectionField;
        
        private string NameField;
        
        private Moryx.Products.UI.ProductService.PartModel[] PartsField;
        
        private Moryx.Products.UI.ProductService.Entry PropertyTemplatesField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName
        {
            get
            {
                return this.DisplayNameField;
            }
            set
            {
                this.DisplayNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCollection
        {
            get
            {
                return this.IsCollectionField;
            }
            set
            {
                this.IsCollectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Products.UI.ProductService.PartModel[] Parts
        {
            get
            {
                return this.PartsField;
            }
            set
            {
                this.PartsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Products.UI.ProductService.Entry PropertyTemplates
        {
            get
            {
                return this.PropertyTemplatesField;
            }
            set
            {
                this.PropertyTemplatesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecipeModel", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Products.Management.Modification")]
    public partial class RecipeModel : object
    {
        
        private Moryx.Products.UI.ProductService.RecipeClassificationModel ClassificationField;
        
        private long IdField;
        
        private string NameField;
        
        private Moryx.Products.UI.ProductService.Entry PropertiesField;
        
        private int RevisionField;
        
        private Moryx.Products.UI.ProductService.RecipeState StateField;
        
        private string TypeField;
        
        private long WorkplanIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Products.UI.ProductService.RecipeClassificationModel Classification
        {
            get
            {
                return this.ClassificationField;
            }
            set
            {
                this.ClassificationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Products.UI.ProductService.Entry Properties
        {
            get
            {
                return this.PropertiesField;
            }
            set
            {
                this.PropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Revision
        {
            get
            {
                return this.RevisionField;
            }
            set
            {
                this.RevisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Products.UI.ProductService.RecipeState State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long WorkplanId
        {
            get
            {
                return this.WorkplanIdField;
            }
            set
            {
                this.WorkplanIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductState", Namespace="http://schemas.datacontract.org/2004/07/Moryx.AbstractionLayer.Products")]
    public enum ProductState : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Created = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Released = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deprecated = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartModel", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Products.Management.Modification")]
    public partial class PartModel : object
    {
        
        private long IdField;
        
        private Moryx.Products.UI.ProductService.ProductModel ProductField;
        
        private Moryx.Products.UI.ProductService.Entry PropertiesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Products.UI.ProductService.ProductModel Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Products.UI.ProductService.Entry Properties
        {
            get
            {
                return this.PropertiesField;
            }
            set
            {
                this.PropertiesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecipeClassificationModel", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Products.Management.Modification")]
    public enum RecipeClassificationModel : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unset = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Default = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Alternative = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Intermediate = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Part = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecipeState", Namespace="http://schemas.datacontract.org/2004/07/Moryx.AbstractionLayer.Recipes")]
    public enum RecipeState : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        New = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Released = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Revoked = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DuplicateProductResponse", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Products.Management.Modification")]
    public partial class DuplicateProductResponse : object
    {
        
        private Moryx.Products.UI.ProductService.ProductModel DuplicateField;
        
        private bool IdentityConflictField;
        
        private bool InvalidSourceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Products.UI.ProductService.ProductModel Duplicate
        {
            get
            {
                return this.DuplicateField;
            }
            set
            {
                this.DuplicateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IdentityConflict
        {
            get
            {
                return this.IdentityConflictField;
            }
            set
            {
                this.IdentityConflictField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InvalidSource
        {
            get
            {
                return this.InvalidSourceField;
            }
            set
            {
                this.InvalidSourceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportStateModel", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Products.Management")]
    public partial class ImportStateModel : object
    {
        
        private bool CompletedField;
        
        private string ErrorMessageField;
        
        private System.Guid SessionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Completed
        {
            get
            {
                return this.CompletedField;
            }
            set
            {
                this.CompletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Session
        {
            get
            {
                return this.SessionField;
            }
            set
            {
                this.SessionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkplanModel", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Products.Management.Modification")]
    public partial class WorkplanModel : object
    {
        
        private long IdField;
        
        private string NameField;
        
        private Moryx.Products.UI.ProductService.WorkplanState StateField;
        
        private int VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Products.UI.ProductService.WorkplanState State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkplanState", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Workflows")]
    public enum WorkplanState : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        New = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Released = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Revoked = 2,
    }
}
