//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moryx.Resources.UI.ResourceService
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceTypeModel", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Resources.Interaction", IsReference=true)]
    public partial class ResourceTypeModel : object
    {
        
        private Moryx.Resources.UI.ResourceService.ResourceTypeModel BaseTypeField;
        
        private Moryx.Resources.UI.ResourceService.MethodEntry[] ConstructorsField;
        
        private bool CreatableField;
        
        private Moryx.Resources.UI.ResourceService.ResourceTypeModel[] DerivedTypesField;
        
        private string DescriptionField;
        
        private string DisplayNameField;
        
        private string NameField;
        
        private Moryx.Resources.UI.ResourceService.ReferenceTypeModel[] ReferencesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Resources.UI.ResourceService.ResourceTypeModel BaseType
        {
            get
            {
                return this.BaseTypeField;
            }
            set
            {
                this.BaseTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Resources.UI.ResourceService.MethodEntry[] Constructors
        {
            get
            {
                return this.ConstructorsField;
            }
            set
            {
                this.ConstructorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Creatable
        {
            get
            {
                return this.CreatableField;
            }
            set
            {
                this.CreatableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Resources.UI.ResourceService.ResourceTypeModel[] DerivedTypes
        {
            get
            {
                return this.DerivedTypesField;
            }
            set
            {
                this.DerivedTypesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName
        {
            get
            {
                return this.DisplayNameField;
            }
            set
            {
                this.DisplayNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Resources.UI.ResourceService.ReferenceTypeModel[] References
        {
            get
            {
                return this.ReferencesField;
            }
            set
            {
                this.ReferencesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MethodEntry", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Serialization")]
    public partial class MethodEntry : object
    {
        
        private string DescriptionField;
        
        private string DisplayNameField;
        
        private string NameField;
        
        private Moryx.Resources.UI.ResourceService.Entry ParametersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName
        {
            get
            {
                return this.DisplayNameField;
            }
            set
            {
                this.DisplayNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Resources.UI.ResourceService.Entry Parameters
        {
            get
            {
                return this.ParametersField;
            }
            set
            {
                this.ParametersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReferenceTypeModel", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Resources.Interaction")]
    public partial class ReferenceTypeModel : object
    {
        
        private string DescriptionField;
        
        private string DisplayNameField;
        
        private bool IsCollectionField;
        
        private bool IsRequiredField;
        
        private string NameField;
        
        private Moryx.Resources.UI.ResourceService.ResourceRelationType RelationTypeField;
        
        private Moryx.Resources.UI.ResourceService.ResourceReferenceRole RoleField;
        
        private string[] SupportedTypesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName
        {
            get
            {
                return this.DisplayNameField;
            }
            set
            {
                this.DisplayNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCollection
        {
            get
            {
                return this.IsCollectionField;
            }
            set
            {
                this.IsCollectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRequired
        {
            get
            {
                return this.IsRequiredField;
            }
            set
            {
                this.IsRequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Resources.UI.ResourceService.ResourceRelationType RelationType
        {
            get
            {
                return this.RelationTypeField;
            }
            set
            {
                this.RelationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Resources.UI.ResourceService.ResourceReferenceRole Role
        {
            get
            {
                return this.RoleField;
            }
            set
            {
                this.RoleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] SupportedTypes
        {
            get
            {
                return this.SupportedTypesField;
            }
            set
            {
                this.SupportedTypesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entry", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Serialization")]
    public partial class Entry : object
    {
        
        private string DescriptionField;
        
        private string DisplayNameField;
        
        private string IdentifierField;
        
        private Moryx.Resources.UI.ResourceService.Entry[] PrototypesField;
        
        private Moryx.Resources.UI.ResourceService.Entry[] SubEntriesField;
        
        private Moryx.Resources.UI.ResourceService.EntryValidation ValidationField;
        
        private Moryx.Resources.UI.ResourceService.EntryValue ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName
        {
            get
            {
                return this.DisplayNameField;
            }
            set
            {
                this.DisplayNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identifier
        {
            get
            {
                return this.IdentifierField;
            }
            set
            {
                this.IdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Resources.UI.ResourceService.Entry[] Prototypes
        {
            get
            {
                return this.PrototypesField;
            }
            set
            {
                this.PrototypesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Resources.UI.ResourceService.Entry[] SubEntries
        {
            get
            {
                return this.SubEntriesField;
            }
            set
            {
                this.SubEntriesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Resources.UI.ResourceService.EntryValidation Validation
        {
            get
            {
                return this.ValidationField;
            }
            set
            {
                this.ValidationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Resources.UI.ResourceService.EntryValue Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntryValidation", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Serialization")]
    public partial class EntryValidation : object
    {
        
        private bool IsRequiredField;
        
        private double MaximumField;
        
        private double MinimumField;
        
        private string RegexField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRequired
        {
            get
            {
                return this.IsRequiredField;
            }
            set
            {
                this.IsRequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Maximum
        {
            get
            {
                return this.MaximumField;
            }
            set
            {
                this.MaximumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Minimum
        {
            get
            {
                return this.MinimumField;
            }
            set
            {
                this.MinimumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Regex
        {
            get
            {
                return this.RegexField;
            }
            set
            {
                this.RegexField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntryValue", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Serialization")]
    public partial class EntryValue : object
    {
        
        private string CurrentField;
        
        private string DefaultField;
        
        private bool IsReadOnlyField;
        
        private string[] PossibleField;
        
        private Moryx.Resources.UI.ResourceService.EntryValueType TypeField;
        
        private Moryx.Resources.UI.ResourceService.EntryUnitType UnitTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Current
        {
            get
            {
                return this.CurrentField;
            }
            set
            {
                this.CurrentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Default
        {
            get
            {
                return this.DefaultField;
            }
            set
            {
                this.DefaultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsReadOnly
        {
            get
            {
                return this.IsReadOnlyField;
            }
            set
            {
                this.IsReadOnlyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Possible
        {
            get
            {
                return this.PossibleField;
            }
            set
            {
                this.PossibleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Resources.UI.ResourceService.EntryValueType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Resources.UI.ResourceService.EntryUnitType UnitType
        {
            get
            {
                return this.UnitTypeField;
            }
            set
            {
                this.UnitTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntryValueType", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Serialization")]
    public enum EntryValueType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Byte = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Boolean = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Int16 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UInt16 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Int32 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UInt32 = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Int64 = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UInt64 = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Single = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Double = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        String = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Enum = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Class = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Collection = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exception = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Stream = 15,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntryUnitType", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Serialization")]
    public enum EntryUnitType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Password = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        File = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Directory = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceRelationType", Namespace="http://schemas.datacontract.org/2004/07/Moryx.AbstractionLayer.Resources")]
    public enum ResourceRelationType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unset = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aggregation = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Composition = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Usage = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ParentChild = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Driver = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TransportSystem = 65,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TransportRoute = 76,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CurrentExchangablePart = 132,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PossibleExchangablePart = 140,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Decorated = 258,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Extension = 265,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Custom = 2147483644,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceReferenceRole", Namespace="http://schemas.datacontract.org/2004/07/Moryx.AbstractionLayer.Resources")]
    public enum ResourceReferenceRole : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Target = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Source = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceQuery", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Resources.Interaction")]
    public partial class ResourceQuery : object
    {
        
        private Moryx.Resources.UI.ResourceService.ReferenceFilter[] IncludedReferencesField;
        
        private Moryx.Resources.UI.ResourceService.ReferenceFilter ReferenceConditionField;
        
        private bool ReferenceRecursionField;
        
        private string[] TypesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Resources.UI.ResourceService.ReferenceFilter[] IncludedReferences
        {
            get
            {
                return this.IncludedReferencesField;
            }
            set
            {
                this.IncludedReferencesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Resources.UI.ResourceService.ReferenceFilter ReferenceCondition
        {
            get
            {
                return this.ReferenceConditionField;
            }
            set
            {
                this.ReferenceConditionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReferenceRecursion
        {
            get
            {
                return this.ReferenceRecursionField;
            }
            set
            {
                this.ReferenceRecursionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Types
        {
            get
            {
                return this.TypesField;
            }
            set
            {
                this.TypesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReferenceFilter", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Resources.Interaction")]
    public partial class ReferenceFilter : object
    {
        
        private string NameField;
        
        private Moryx.Resources.UI.ResourceService.ResourceRelationType RelationTypeField;
        
        private Moryx.Resources.UI.ResourceService.ResourceReferenceRole RoleField;
        
        private Moryx.Resources.UI.ResourceService.ReferenceValue ValueConstraintField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Resources.UI.ResourceService.ResourceRelationType RelationType
        {
            get
            {
                return this.RelationTypeField;
            }
            set
            {
                this.RelationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Resources.UI.ResourceService.ResourceReferenceRole Role
        {
            get
            {
                return this.RoleField;
            }
            set
            {
                this.RoleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Resources.UI.ResourceService.ReferenceValue ValueConstraint
        {
            get
            {
                return this.ValueConstraintField;
            }
            set
            {
                this.ValueConstraintField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReferenceValue", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Resources.Interaction")]
    public enum ReferenceValue : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Irrelevant = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NullOrEmpty = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEmpty = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceModel", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Resources.Interaction", IsReference=true)]
    public partial class ResourceModel : object
    {
        
        private string DescriptionField;
        
        private long IdField;
        
        private Moryx.Resources.UI.ResourceService.MethodEntry[] MethodsField;
        
        private string NameField;
        
        private bool PartiallyLoadedField;
        
        private Moryx.Resources.UI.ResourceService.Entry PropertiesField;
        
        private Moryx.Resources.UI.ResourceService.ResourceReferenceModel[] ReferencesField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Resources.UI.ResourceService.MethodEntry[] Methods
        {
            get
            {
                return this.MethodsField;
            }
            set
            {
                this.MethodsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PartiallyLoaded
        {
            get
            {
                return this.PartiallyLoadedField;
            }
            set
            {
                this.PartiallyLoadedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Resources.UI.ResourceService.Entry Properties
        {
            get
            {
                return this.PropertiesField;
            }
            set
            {
                this.PropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Resources.UI.ResourceService.ResourceReferenceModel[] References
        {
            get
            {
                return this.ReferencesField;
            }
            set
            {
                this.ReferencesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceReferenceModel", Namespace="http://schemas.datacontract.org/2004/07/Moryx.Resources.Interaction", IsReference=true)]
    public partial class ResourceReferenceModel : object
    {
        
        private string NameField;
        
        private Moryx.Resources.UI.ResourceService.ResourceModel[] TargetsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moryx.Resources.UI.ResourceService.ResourceModel[] Targets
        {
            get
            {
                return this.TargetsField;
            }
            set
            {
                this.TargetsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Moryx.Resources.UI.ResourceService.IResourceInteraction")]
    public interface IResourceInteraction
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceInteraction/GetTypeTree", ReplyAction="http://tempuri.org/IResourceInteraction/GetTypeTreeResponse")]
        System.Threading.Tasks.Task<Moryx.Resources.UI.ResourceService.ResourceTypeModel> GetTypeTreeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceInteraction/GetResources", ReplyAction="http://tempuri.org/IResourceInteraction/GetResourcesResponse")]
        System.Threading.Tasks.Task<Moryx.Resources.UI.ResourceService.ResourceModel[]> GetResourcesAsync(Moryx.Resources.UI.ResourceService.ResourceQuery query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceInteraction/GetDetails", ReplyAction="http://tempuri.org/IResourceInteraction/GetDetailsResponse")]
        System.Threading.Tasks.Task<Moryx.Resources.UI.ResourceService.ResourceModel[]> GetDetailsAsync(long[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceInteraction/InvokeMethod", ReplyAction="http://tempuri.org/IResourceInteraction/InvokeMethodResponse")]
        System.Threading.Tasks.Task<Moryx.Resources.UI.ResourceService.Entry> InvokeMethodAsync(long id, Moryx.Resources.UI.ResourceService.MethodEntry method);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceInteraction/Create", ReplyAction="http://tempuri.org/IResourceInteraction/CreateResponse")]
        System.Threading.Tasks.Task<Moryx.Resources.UI.ResourceService.ResourceModel> CreateAsync(string resourceType, Moryx.Resources.UI.ResourceService.MethodEntry constructor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceInteraction/Save", ReplyAction="http://tempuri.org/IResourceInteraction/SaveResponse")]
        System.Threading.Tasks.Task<Moryx.Resources.UI.ResourceService.ResourceModel> SaveAsync(Moryx.Resources.UI.ResourceService.ResourceModel resource);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceInteraction/Remove", ReplyAction="http://tempuri.org/IResourceInteraction/RemoveResponse")]
        System.Threading.Tasks.Task<bool> RemoveAsync(long id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IResourceInteractionChannel : Moryx.Resources.UI.ResourceService.IResourceInteraction, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ResourceInteractionClient : System.ServiceModel.ClientBase<Moryx.Resources.UI.ResourceService.IResourceInteraction>, Moryx.Resources.UI.ResourceService.IResourceInteraction
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ResourceInteractionClient() : 
                base(ResourceInteractionClient.GetDefaultBinding(), ResourceInteractionClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IResourceInteraction.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ResourceInteractionClient(EndpointConfiguration endpointConfiguration) : 
                base(ResourceInteractionClient.GetBindingForEndpoint(endpointConfiguration), ResourceInteractionClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ResourceInteractionClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ResourceInteractionClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ResourceInteractionClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ResourceInteractionClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ResourceInteractionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Moryx.Resources.UI.ResourceService.ResourceTypeModel> GetTypeTreeAsync()
        {
            return base.Channel.GetTypeTreeAsync();
        }
        
        public System.Threading.Tasks.Task<Moryx.Resources.UI.ResourceService.ResourceModel[]> GetResourcesAsync(Moryx.Resources.UI.ResourceService.ResourceQuery query)
        {
            return base.Channel.GetResourcesAsync(query);
        }
        
        public System.Threading.Tasks.Task<Moryx.Resources.UI.ResourceService.ResourceModel[]> GetDetailsAsync(long[] ids)
        {
            return base.Channel.GetDetailsAsync(ids);
        }
        
        public System.Threading.Tasks.Task<Moryx.Resources.UI.ResourceService.Entry> InvokeMethodAsync(long id, Moryx.Resources.UI.ResourceService.MethodEntry method)
        {
            return base.Channel.InvokeMethodAsync(id, method);
        }
        
        public System.Threading.Tasks.Task<Moryx.Resources.UI.ResourceService.ResourceModel> CreateAsync(string resourceType, Moryx.Resources.UI.ResourceService.MethodEntry constructor)
        {
            return base.Channel.CreateAsync(resourceType, constructor);
        }
        
        public System.Threading.Tasks.Task<Moryx.Resources.UI.ResourceService.ResourceModel> SaveAsync(Moryx.Resources.UI.ResourceService.ResourceModel resource)
        {
            return base.Channel.SaveAsync(resource);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveAsync(long id)
        {
            return base.Channel.RemoveAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IResourceInteraction))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IResourceInteraction))
            {
                return new System.ServiceModel.EndpointAddress("http://pxc-n2488/ResourceInteraction");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ResourceInteractionClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IResourceInteraction);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ResourceInteractionClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IResourceInteraction);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IResourceInteraction,
        }
    }
}
