// Copyright (c) 2020, Phoenix Contact GmbH & Co. KG
// Licensed under the Apache License, Version 2.0

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marvin.Resources.UI.ResourceService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceTypeModel", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Resources.Interaction", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ResourceTypeModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Resources.UI.ResourceService.ResourceTypeModel BaseTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Serialization.MethodEntry[] ConstructorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CreatableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Resources.UI.ResourceService.ResourceTypeModel[] DerivedTypesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Resources.UI.ResourceService.ReferenceTypeModel[] ReferencesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Resources.UI.ResourceService.ResourceTypeModel BaseType {
            get {
                return this.BaseTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.BaseTypeField, value) != true)) {
                    this.BaseTypeField = value;
                    this.RaisePropertyChanged("BaseType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Serialization.MethodEntry[] Constructors {
            get {
                return this.ConstructorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ConstructorsField, value) != true)) {
                    this.ConstructorsField = value;
                    this.RaisePropertyChanged("Constructors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Creatable {
            get {
                return this.CreatableField;
            }
            set {
                if ((this.CreatableField.Equals(value) != true)) {
                    this.CreatableField = value;
                    this.RaisePropertyChanged("Creatable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Resources.UI.ResourceService.ResourceTypeModel[] DerivedTypes {
            get {
                return this.DerivedTypesField;
            }
            set {
                if ((object.ReferenceEquals(this.DerivedTypesField, value) != true)) {
                    this.DerivedTypesField = value;
                    this.RaisePropertyChanged("DerivedTypes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Resources.UI.ResourceService.ReferenceTypeModel[] References {
            get {
                return this.ReferencesField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferencesField, value) != true)) {
                    this.ReferencesField = value;
                    this.RaisePropertyChanged("References");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReferenceTypeModel", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Resources.Interaction")]
    [System.SerializableAttribute()]
    public partial class ReferenceTypeModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCollectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Resources.UI.ResourceService.ResourceRelationType RelationTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Resources.UI.ResourceService.ResourceReferenceRole RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SupportedTypesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCollection {
            get {
                return this.IsCollectionField;
            }
            set {
                if ((this.IsCollectionField.Equals(value) != true)) {
                    this.IsCollectionField = value;
                    this.RaisePropertyChanged("IsCollection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRequired {
            get {
                return this.IsRequiredField;
            }
            set {
                if ((this.IsRequiredField.Equals(value) != true)) {
                    this.IsRequiredField = value;
                    this.RaisePropertyChanged("IsRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Resources.UI.ResourceService.ResourceRelationType RelationType {
            get {
                return this.RelationTypeField;
            }
            set {
                if ((this.RelationTypeField.Equals(value) != true)) {
                    this.RelationTypeField = value;
                    this.RaisePropertyChanged("RelationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Resources.UI.ResourceService.ResourceReferenceRole Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] SupportedTypes {
            get {
                return this.SupportedTypesField;
            }
            set {
                if ((object.ReferenceEquals(this.SupportedTypesField, value) != true)) {
                    this.SupportedTypesField = value;
                    this.RaisePropertyChanged("SupportedTypes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceRelationType", Namespace="http://schemas.datacontract.org/2004/07/Marvin.AbstractionLayer.Resources")]
    public enum ResourceRelationType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unset = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aggregation = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Composition = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Usage = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ParentChild = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Driver = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TransportSystem = 65,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TransportRoute = 76,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CurrentExchangablePart = 132,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PossibleExchangablePart = 140,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Decorated = 258,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Extension = 265,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Custom = 2147483644,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceReferenceRole", Namespace="http://schemas.datacontract.org/2004/07/Marvin.AbstractionLayer.Resources")]
    public enum ResourceReferenceRole : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Target = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Source = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceQuery", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Resources.Interaction")]
    [System.SerializableAttribute()]
    public partial class ResourceQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Resources.UI.ResourceService.ReferenceFilter[] IncludedReferencesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Resources.UI.ResourceService.ReferenceFilter ReferenceConditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ReferenceRecursionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] TypesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Resources.UI.ResourceService.ReferenceFilter[] IncludedReferences {
            get {
                return this.IncludedReferencesField;
            }
            set {
                if ((object.ReferenceEquals(this.IncludedReferencesField, value) != true)) {
                    this.IncludedReferencesField = value;
                    this.RaisePropertyChanged("IncludedReferences");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Resources.UI.ResourceService.ReferenceFilter ReferenceCondition {
            get {
                return this.ReferenceConditionField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceConditionField, value) != true)) {
                    this.ReferenceConditionField = value;
                    this.RaisePropertyChanged("ReferenceCondition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReferenceRecursion {
            get {
                return this.ReferenceRecursionField;
            }
            set {
                if ((this.ReferenceRecursionField.Equals(value) != true)) {
                    this.ReferenceRecursionField = value;
                    this.RaisePropertyChanged("ReferenceRecursion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Types {
            get {
                return this.TypesField;
            }
            set {
                if ((object.ReferenceEquals(this.TypesField, value) != true)) {
                    this.TypesField = value;
                    this.RaisePropertyChanged("Types");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReferenceFilter", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Resources.Interaction")]
    [System.SerializableAttribute()]
    public partial class ReferenceFilter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Resources.UI.ResourceService.ResourceRelationType RelationTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Resources.UI.ResourceService.ResourceReferenceRole RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Resources.UI.ResourceService.ReferenceValue ValueConstraintField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Resources.UI.ResourceService.ResourceRelationType RelationType {
            get {
                return this.RelationTypeField;
            }
            set {
                if ((this.RelationTypeField.Equals(value) != true)) {
                    this.RelationTypeField = value;
                    this.RaisePropertyChanged("RelationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Resources.UI.ResourceService.ResourceReferenceRole Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Resources.UI.ResourceService.ReferenceValue ValueConstraint {
            get {
                return this.ValueConstraintField;
            }
            set {
                if ((this.ValueConstraintField.Equals(value) != true)) {
                    this.ValueConstraintField = value;
                    this.RaisePropertyChanged("ValueConstraint");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReferenceValue", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Resources.Interaction")]
    public enum ReferenceValue : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Irrelevant = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NullOrEmpty = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEmpty = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceModel", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Resources.Interaction", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ResourceModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Serialization.MethodEntry[] MethodsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PartiallyLoadedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Serialization.Entry PropertiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Resources.UI.ResourceService.ResourceReferenceModel[] ReferencesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Serialization.MethodEntry[] Methods {
            get {
                return this.MethodsField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodsField, value) != true)) {
                    this.MethodsField = value;
                    this.RaisePropertyChanged("Methods");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PartiallyLoaded {
            get {
                return this.PartiallyLoadedField;
            }
            set {
                if ((this.PartiallyLoadedField.Equals(value) != true)) {
                    this.PartiallyLoadedField = value;
                    this.RaisePropertyChanged("PartiallyLoaded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Serialization.Entry Properties {
            get {
                return this.PropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertiesField, value) != true)) {
                    this.PropertiesField = value;
                    this.RaisePropertyChanged("Properties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Resources.UI.ResourceService.ResourceReferenceModel[] References {
            get {
                return this.ReferencesField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferencesField, value) != true)) {
                    this.ReferencesField = value;
                    this.RaisePropertyChanged("References");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceReferenceModel", Namespace="http://schemas.datacontract.org/2004/07/Marvin.Resources.Interaction", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ResourceReferenceModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Marvin.Resources.UI.ResourceService.ResourceModel[] TargetsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Marvin.Resources.UI.ResourceService.ResourceModel[] Targets {
            get {
                return this.TargetsField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetsField, value) != true)) {
                    this.TargetsField = value;
                    this.RaisePropertyChanged("Targets");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ResourceService.IResourceInteraction")]
    public interface IResourceInteraction {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceInteraction/GetTypeTree", ReplyAction="http://tempuri.org/IResourceInteraction/GetTypeTreeResponse")]
        Marvin.Resources.UI.ResourceService.ResourceTypeModel GetTypeTree();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceInteraction/GetTypeTree", ReplyAction="http://tempuri.org/IResourceInteraction/GetTypeTreeResponse")]
        System.Threading.Tasks.Task<Marvin.Resources.UI.ResourceService.ResourceTypeModel> GetTypeTreeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceInteraction/GetResources", ReplyAction="http://tempuri.org/IResourceInteraction/GetResourcesResponse")]
        Marvin.Resources.UI.ResourceService.ResourceModel[] GetResources(Marvin.Resources.UI.ResourceService.ResourceQuery query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceInteraction/GetResources", ReplyAction="http://tempuri.org/IResourceInteraction/GetResourcesResponse")]
        System.Threading.Tasks.Task<Marvin.Resources.UI.ResourceService.ResourceModel[]> GetResourcesAsync(Marvin.Resources.UI.ResourceService.ResourceQuery query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceInteraction/GetDetails", ReplyAction="http://tempuri.org/IResourceInteraction/GetDetailsResponse")]
        Marvin.Resources.UI.ResourceService.ResourceModel[] GetDetails(long[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceInteraction/GetDetails", ReplyAction="http://tempuri.org/IResourceInteraction/GetDetailsResponse")]
        System.Threading.Tasks.Task<Marvin.Resources.UI.ResourceService.ResourceModel[]> GetDetailsAsync(long[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceInteraction/InvokeMethod", ReplyAction="http://tempuri.org/IResourceInteraction/InvokeMethodResponse")]
        Marvin.Serialization.Entry InvokeMethod(long id, Marvin.Serialization.MethodEntry method);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceInteraction/InvokeMethod", ReplyAction="http://tempuri.org/IResourceInteraction/InvokeMethodResponse")]
        System.Threading.Tasks.Task<Marvin.Serialization.Entry> InvokeMethodAsync(long id, Marvin.Serialization.MethodEntry method);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceInteraction/Create", ReplyAction="http://tempuri.org/IResourceInteraction/CreateResponse")]
        Marvin.Resources.UI.ResourceService.ResourceModel Create(string resourceType, Marvin.Serialization.MethodEntry constructor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceInteraction/Create", ReplyAction="http://tempuri.org/IResourceInteraction/CreateResponse")]
        System.Threading.Tasks.Task<Marvin.Resources.UI.ResourceService.ResourceModel> CreateAsync(string resourceType, Marvin.Serialization.MethodEntry constructor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceInteraction/Save", ReplyAction="http://tempuri.org/IResourceInteraction/SaveResponse")]
        Marvin.Resources.UI.ResourceService.ResourceModel Save(Marvin.Resources.UI.ResourceService.ResourceModel resource);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceInteraction/Save", ReplyAction="http://tempuri.org/IResourceInteraction/SaveResponse")]
        System.Threading.Tasks.Task<Marvin.Resources.UI.ResourceService.ResourceModel> SaveAsync(Marvin.Resources.UI.ResourceService.ResourceModel resource);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceInteraction/Remove", ReplyAction="http://tempuri.org/IResourceInteraction/RemoveResponse")]
        bool Remove(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceInteraction/Remove", ReplyAction="http://tempuri.org/IResourceInteraction/RemoveResponse")]
        System.Threading.Tasks.Task<bool> RemoveAsync(long id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IResourceInteractionChannel : Marvin.Resources.UI.ResourceService.IResourceInteraction, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResourceInteractionClient : System.ServiceModel.ClientBase<Marvin.Resources.UI.ResourceService.IResourceInteraction>, Marvin.Resources.UI.ResourceService.IResourceInteraction {
        
        public ResourceInteractionClient() {
        }
        
        public ResourceInteractionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResourceInteractionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResourceInteractionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResourceInteractionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Marvin.Resources.UI.ResourceService.ResourceTypeModel GetTypeTree() {
            return base.Channel.GetTypeTree();
        }
        
        public System.Threading.Tasks.Task<Marvin.Resources.UI.ResourceService.ResourceTypeModel> GetTypeTreeAsync() {
            return base.Channel.GetTypeTreeAsync();
        }
        
        public Marvin.Resources.UI.ResourceService.ResourceModel[] GetResources(Marvin.Resources.UI.ResourceService.ResourceQuery query) {
            return base.Channel.GetResources(query);
        }
        
        public System.Threading.Tasks.Task<Marvin.Resources.UI.ResourceService.ResourceModel[]> GetResourcesAsync(Marvin.Resources.UI.ResourceService.ResourceQuery query) {
            return base.Channel.GetResourcesAsync(query);
        }
        
        public Marvin.Resources.UI.ResourceService.ResourceModel[] GetDetails(long[] ids) {
            return base.Channel.GetDetails(ids);
        }
        
        public System.Threading.Tasks.Task<Marvin.Resources.UI.ResourceService.ResourceModel[]> GetDetailsAsync(long[] ids) {
            return base.Channel.GetDetailsAsync(ids);
        }
        
        public Marvin.Serialization.Entry InvokeMethod(long id, Marvin.Serialization.MethodEntry method) {
            return base.Channel.InvokeMethod(id, method);
        }
        
        public System.Threading.Tasks.Task<Marvin.Serialization.Entry> InvokeMethodAsync(long id, Marvin.Serialization.MethodEntry method) {
            return base.Channel.InvokeMethodAsync(id, method);
        }
        
        public Marvin.Resources.UI.ResourceService.ResourceModel Create(string resourceType, Marvin.Serialization.MethodEntry constructor) {
            return base.Channel.Create(resourceType, constructor);
        }
        
        public System.Threading.Tasks.Task<Marvin.Resources.UI.ResourceService.ResourceModel> CreateAsync(string resourceType, Marvin.Serialization.MethodEntry constructor) {
            return base.Channel.CreateAsync(resourceType, constructor);
        }
        
        public Marvin.Resources.UI.ResourceService.ResourceModel Save(Marvin.Resources.UI.ResourceService.ResourceModel resource) {
            return base.Channel.Save(resource);
        }
        
        public System.Threading.Tasks.Task<Marvin.Resources.UI.ResourceService.ResourceModel> SaveAsync(Marvin.Resources.UI.ResourceService.ResourceModel resource) {
            return base.Channel.SaveAsync(resource);
        }
        
        public bool Remove(long id) {
            return base.Channel.Remove(id);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveAsync(long id) {
            return base.Channel.RemoveAsync(id);
        }
    }
}
