//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marvin.Resources.UI.Interaction.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marvin.Resources.UI.Interaction.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string AspectConfiguratorView_DisplayName {
            get {
                return ResourceManager.GetString("AspectConfiguratorView_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a resource from the tree on the left side..
        /// </summary>
        internal static string EmptyDetailsView_SelectResource {
            get {
                return ResourceManager.GetString("EmptyDetailsView_SelectResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string InteractionWorkspaceView_Add {
            get {
                return ResourceManager.GetString("InteractionWorkspaceView_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string InteractionWorkspaceView_Cancel {
            get {
                return ResourceManager.GetString("InteractionWorkspaceView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string InteractionWorkspaceView_Description {
            get {
                return ResourceManager.GetString("InteractionWorkspaceView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string InteractionWorkspaceView_Edit {
            get {
                return ResourceManager.GetString("InteractionWorkspaceView_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Identifier:.
        /// </summary>
        internal static string InteractionWorkspaceView_GlobalIdentifier {
            get {
                return ResourceManager.GetString("InteractionWorkspaceView_GlobalIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Identifier:.
        /// </summary>
        internal static string InteractionWorkspaceView_LocalIdentifier {
            get {
                return ResourceManager.GetString("InteractionWorkspaceView_LocalIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string InteractionWorkspaceView_Name {
            get {
                return ResourceManager.GetString("InteractionWorkspaceView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string InteractionWorkspaceView_Remove {
            get {
                return ResourceManager.GetString("InteractionWorkspaceView_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        internal static string InteractionWorkspaceView_Resources {
            get {
                return ResourceManager.GetString("InteractionWorkspaceView_Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string InteractionWorkspaceView_Save {
            get {
                return ResourceManager.GetString("InteractionWorkspaceView_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        internal static string ModuleController_DisplayName {
            get {
                return ResourceManager.GetString("ModuleController_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string PropertiesAspectViewModel_DisplayName {
            get {
                return ResourceManager.GetString("PropertiesAspectViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Target.
        /// </summary>
        internal static string ReferencesAspectView_AddTarget {
            get {
                return ResourceManager.GetString("ReferencesAspectView_AddTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string ReferencesAspectView_Description {
            get {
                return ResourceManager.GetString("ReferencesAspectView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Identifier.
        /// </summary>
        internal static string ReferencesAspectView_GlobalIdentifier {
            get {
                return ResourceManager.GetString("ReferencesAspectView_GlobalIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Target.
        /// </summary>
        internal static string ReferencesAspectView_LinkTarget {
            get {
                return ResourceManager.GetString("ReferencesAspectView_LinkTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Identifier.
        /// </summary>
        internal static string ReferencesAspectView_LocalIdentifier {
            get {
                return ResourceManager.GetString("ReferencesAspectView_LocalIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ReferencesAspectView_Name {
            get {
                return ResourceManager.GetString("ReferencesAspectView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference:.
        /// </summary>
        internal static string ReferencesAspectView_Reference {
            get {
                return ResourceManager.GetString("ReferencesAspectView_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This reference is required and must be set!.
        /// </summary>
        internal static string ReferencesAspectView_RequiredReference {
            get {
                return ResourceManager.GetString("ReferencesAspectView_RequiredReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This reference currently has not target..
        /// </summary>
        internal static string ReferencesAspectView_SingleReference_TargetNull {
            get {
                return ResourceManager.GetString("ReferencesAspectView_SingleReference_TargetNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ReferencesAspectView_Type {
            get {
                return ResourceManager.GetString("ReferencesAspectView_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlink Target.
        /// </summary>
        internal static string ReferencesAspectView_UnlinkTarget {
            get {
                return ResourceManager.GetString("ReferencesAspectView_UnlinkTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        internal static string ReferencesAspectViewModel_DisplayName {
            get {
                return ResourceManager.GetString("ReferencesAspectViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference must have at least one target!.
        /// </summary>
        internal static string ReferencesAspectViewModel_Validation_CollectionTargetMustBeSet {
            get {
                return ResourceManager.GetString("ReferencesAspectViewModel_Validation_CollectionTargetMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single references must have any target!.
        /// </summary>
        internal static string ReferencesAspectViewModel_Validation_SingleTargetMustBeSet {
            get {
                return ResourceManager.GetString("ReferencesAspectViewModel_Validation_SingleTargetMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string RemoveResourceView_Cancel {
            get {
                return ResourceManager.GetString("RemoveResourceView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following resource will be irreversible removed:.
        /// </summary>
        internal static string RemoveResourceView_Description {
            get {
                return ResourceManager.GetString("RemoveResourceView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string RemoveResourceView_Remove {
            get {
                return ResourceManager.GetString("RemoveResourceView_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Resource.
        /// </summary>
        internal static string RemoveResourceViewModel_DisplayName {
            get {
                return ResourceManager.GetString("RemoveResourceViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource was not removed!.
        /// </summary>
        internal static string RemoveResourceViewModel_ErrorWhileRemove {
            get {
                return ResourceManager.GetString("RemoveResourceViewModel_ErrorWhileRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string ResourceMethodsAspectView_Description {
            get {
                return ResourceManager.GetString("ResourceMethodsAspectView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke.
        /// </summary>
        internal static string ResourceMethodsAspectView_Invoke {
            get {
                return ResourceManager.GetString("ResourceMethodsAspectView_Invoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method was invoked.
        /// </summary>
        internal static string ResourceMethodsAspectView_Invoked {
            get {
                return ResourceManager.GetString("ResourceMethodsAspectView_Invoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method:.
        /// </summary>
        internal static string ResourceMethodsAspectView_Method {
            get {
                return ResourceManager.GetString("ResourceMethodsAspectView_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no parameters necessary for this method call.
        /// </summary>
        internal static string ResourceMethodsAspectView_NoParametersNeeded {
            get {
                return ResourceManager.GetString("ResourceMethodsAspectView_NoParametersNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string ResourceMethodsAspectView_Result {
            get {
                return ResourceManager.GetString("ResourceMethodsAspectView_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a method to invoke it.
        /// </summary>
        internal static string ResourceMethodsAspectView_SelectMethod {
            get {
                return ResourceManager.GetString("ResourceMethodsAspectView_SelectMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods.
        /// </summary>
        internal static string ResourceMethodsAspectViewModel_DisplayName {
            get {
                return ResourceManager.GetString("ResourceMethodsAspectViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select new target.
        /// </summary>
        internal static string SelectTargetDialogViewModel_DisplayName {
            get {
                return ResourceManager.GetString("SelectTargetDialogViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string TypeSelectorView_Cancel {
            get {
                return ResourceManager.GetString("TypeSelectorView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string TypeSelectorView_Create {
            get {
                return ResourceManager.GetString("TypeSelectorView_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string TypeSelectorView_Description {
            get {
                return ResourceManager.GetString("TypeSelectorView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal:.
        /// </summary>
        internal static string TypeSelectorView_Internal {
            get {
                return ResourceManager.GetString("TypeSelectorView_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string TypeSelectorView_Name {
            get {
                return ResourceManager.GetString("TypeSelectorView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the resource type to create a resource instance..
        /// </summary>
        internal static string TypeSelectorView_SelectResourceType {
            get {
                return ResourceManager.GetString("TypeSelectorView_SelectResourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource type selection:.
        /// </summary>
        internal static string TypeSelectorViewModel_DisplayName {
            get {
                return ResourceManager.GetString("TypeSelectorViewModel_DisplayName", resourceCulture);
            }
        }
    }
}
